IF
    CutSceneBroken()
THEN
    RESPONSE #100
        SetCutSceneBreakable(FALSE)
        StartCutSceneMode()
        ClearAllActions()
        FadeToColor([0.0],0)
        SetCursorState(FALSE)
        SetAreaScript("",OVERRIDE)
        SetGlobal("ZBNEPH_CUTSCENE_BREAKABLE","GLOBAL",0)
        Continue()
END

IF
    CutSceneBroken()
    Switch("ZBNEPH_CUTSCENE_BREAKABLE","GLOBAL")
THEN
    RESPONSE #1
    ActionOverride("zspdnf16",DestroySelf())
	ActionOverride("zbvamp",DestroySelf())
	Wait(1)
    RestorePartyLocations()
	Wait(1) 
	EndCutSceneMode() /* exits the the StartCutSceneMode() action */
	FadeFromColor([50.0],0)
	AddJournalEntry(@800001,QUEST) /* add journal entry, moved over from d file */ 
    GiveItemCreate("zbpdnote",Player1,1,0,0) /* give player the note, moved over from d file */ 
END
