IF
	GlobalGT("ohb_finale","global",2)
	Global("ohb_cook_dead","global",1)
	See([PC])
	Range(LastSeenBy(Myself),25)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END

IF
	Global("ohb_finale","global",5)
	Global("ohb_cook_dead","global",2)
	Global("ohb_finale_move","locals",0)
THEN
	RESPONSE #100
		SetGlobal("ohb_finale_move","locals",1)
		JumpToPoint([4055.3220])
		MoveToPoint([4055.3220])
		Face(NW)
END

