IF
    Clicked([ANYONE])
    Range(LastTrigger,10)
    Global("OHB_DAIS_LEVER","OH8400",0)  // TBP2 - Arena 3
THEN
    RESPONSE #100
        DisplayString(Myself,456)  // Doors have opened
        SetGlobal("OHB_DAIS_LEVER","OH8400",1)  // TBP2 - Arena 3
END

IF
    Clicked([ANYONE])
    !Range(LastTrigger,10)
THEN
    RESPONSE #100
        DisplayString(Myself,14702)  // You are too far away to use that.
END
