IF
	Die()
	Race(Myself,VAMPIRE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		ReallyForceSpellDead(Myself,VAMPIRE_GAS_FORM_CHANGE)  // SPIN964.SPL (No such index)
		EscapeAreaDestroy(15)
		SetInterrupt(TRUE)
END

IF
	Global("OH_Active","LOCALS",0)
	OR(3)
		See(NearestEnemyOf(Myself))
		AttackedBy([ANYONE],DEFAULT)
		TookDamage()
THEN
	RESPONSE #100
		SetGlobal("OH_Active","LOCALS",1)
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		Enemy()
		Shout(ASSIST)
		Continue()
END

IF
	Global("OH_Active","LOCALS",0)
	Heard([EVILCUTOFF],ASSIST)
	Range(LastHeardBy(Myself),25)
THEN
	RESPONSE #100
		SetGlobal("OH_Active","LOCALS",1)
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		Enemy()
		Shout(ASSIST)
		MoveToObject(LastHeardBy(Myself))
END

IF
	Global("OH_Active","LOCALS",1)
	Global("OH_CHCntg","LOCALS",0)
	See(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("OH_CHCntg","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
		ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
		Continue()
END

IF
	Global("OH_Active","LOCALS",1)
	Global("OH_Cntg","LOCALS",0)
	LevelGT(Myself,11)
	!StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("OH_Cntg","LOCALS",1)
		DisplayString(Myself,8292)  // Contingency Active
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		Continue()
END

IF
	OR(5)
		Global("OH_Active","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_PANIC)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!GlobalTimerNotExpired("OH_Rest","LOCALS")
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		SetGlobal("OH_CHCntg","LOCALS",0)
		SetGlobal("OH_Cntg","LOCALS",0)
		SetGlobal("OH_Seq","LOCALS",0)
		SetGlobal("OH_MSeq","LOCALS",0)
		SetGlobal("OH_Trig","LOCALS",0)
		ApplySpell(Myself,RESTORE_FULL_HEALTH)  // SPIN746.SPL (No such index)
		Rest()
		SetInterrupt(TRUE)
END

IF
	Global("OH_Heal","LOCALS",1)
	OR(2)
		HPPercentGT(Myself,84)
		!HasItem("POTN52",Myself)  // Potion of Extra Healing
THEN
	RESPONSE #100
		SetGlobal("OH_Heal","LOCALS",0)
END

IF
	HPPercentLT(Myself,85)
	Global("OH_Heal","LOCALS",0)
	HasItem("POTN52",Myself)  // Potion of Extra Healing
THEN
	RESPONSE #100
		SetGlobal("OH_Heal","LOCALS",1)
END

IF
	Global("OH_Heal","LOCALS",1)
	!StateCheck(Myself,STATE_INVISIBLE)
	!Global("dvgldust","LOCALS",1)
	HasItem("POTN10",Myself)  // Potion of Invisibility
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!CheckStatGT(Player1,0,TRUE_SIGHT)
	!CheckStatGT(Player2,0,TRUE_SIGHT)
	!CheckStatGT(Player3,0,TRUE_SIGHT)
	!CheckStatGT(Player4,0,TRUE_SIGHT)
	!CheckStatGT(Player5,0,TRUE_SIGHT)
	!CheckStatGT(Player6,0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		UseItem("POTN10",Myself)  // Potion of Invisibility
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
END

IF
	Global("OH_Heal","LOCALS",1)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HasItem("POTN52",Myself)  // Potion of Extra Healing
	HPPercentLT(Myself,85)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		UseItem("POTN52",Myself)  // Potion of Extra Healing
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
END

IF
	Global("OH_Active","LOCALS",1)
	Global("OH_CHCntg","LOCALS",0)
	!StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("OH_CHCntg","LOCALS",1)
		DisplayString(Myself,26328)  // Chain Contingency
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
		ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
		ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
		Continue()
END

IF
	Global("OH_Active","LOCALS",1)
	Global("OH_Cntg","LOCALS",0)
	!StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("OH_Cntg","LOCALS",1)
		DisplayString(Myself,8292)  // Contingency Active
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		Continue()
END

IF
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	Global("OH_Trig","LOCALS",0)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	Range([GOODCUTOFF],30)
	!StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetGlobal("OH_Trig","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		DisplayString(Myself,26243)  // Spell Trigger
		ReallyForceSpell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
END

IF
	StateCheck(Myself,STATE_SILENCED)
	HaveSpell(WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	Global("OH_Seq","LOCALS",0)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	CheckStatLT(Myself,1,STONESKINS)
	CheckStat(Myself,0,WIZARD_FIRE_SHIELD)
	Range([GOODCUTOFF],30)
THEN
	RESPONSE #100
		SetGlobal("OH_Seq","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		DisplayString(Myself,39969)  // Spell Sequencer—Fired
		ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
		ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	Range([GOODCUTOFF],30)
	HaveSpell(WIZARD_TIME_STOP)  // SPWI909.SPL (Time Stop)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_TStop","LOCALS",THREE_ROUNDS)
		Spell(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (Time Stop)
END

IF
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (Improved Alacrity)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	Range([GOODCUTOFF],30)
	DifficultyGT(EASY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (Improved Alacrity)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	Range([GOODCUTOFF],30)
	OR(3)
		CheckStatLT(Myself,1,STONESKINS)
		AttackedBy([ANYONE],DEFAULT)
		Range([GOODCUTOFF],4)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	CheckStatLT(Myself,1,STONESKINS)
	HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
	OR(3)
		See([GOODCUTOFF.0.0.0.0.SUMMONED])
		See([GOODCUTOFF.WEAPON.SWORD.0.0.SUMMONED])
		See([GOODCUTOFF.0.MIST.0.0.SUMMONED])
	OR(3)
		HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
		HasItem("NISHRUU",LastSeenBy(Myself))  // Attack
		NumCreatureGT([GOODCUTOFF.0.0.0.0.SUMMONED],2)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	See([GOODCUTOFF.WEAPON.SWORD.0.0.SUMMONED])
	HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
	DifficultyGT(EASY)
	HPLT(Player1,60)
	See(Player1)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player1)  // Cloak of Mirroring
	!CheckStatGT(Player1,0,SANCTUARY)
	!CheckStatGT(Player1,0,DEATH_WARD)
	!CheckStatGT(Player1,1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player1,1,WIZARD_SPELL_TURNING)
	!CheckStatGT(Player1,0,WIZARD_SPELL_TRAP)
	!CheckStat(Player1,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player1,2,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Player1,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
	DifficultyGT(EASY)
	HPLT(Player2,60)
	See(Player2)
	!StateCheck(Player2,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player2)  // Cloak of Mirroring
	!CheckStatGT(Player2,0,SANCTUARY)
	!CheckStatGT(Player2,0,DEATH_WARD)
	!CheckStatGT(Player2,1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player2,1,WIZARD_SPELL_TURNING)
	!CheckStatGT(Player2,0,WIZARD_SPELL_TRAP)
	!CheckStat(Player2,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player2,2,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Player2,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
	DifficultyGT(EASY)
	HPLT(Player3,60)
	See(Player3)
	!StateCheck(Player3,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player3)  // Cloak of Mirroring
	!CheckStatGT(Player3,0,SANCTUARY)
	!CheckStatGT(Player3,0,DEATH_WARD)
	!CheckStatGT(Player3,1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player3,1,WIZARD_SPELL_TURNING)
	!CheckStatGT(Player3,0,WIZARD_SPELL_TRAP)
	!CheckStat(Player3,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player3,2,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Player3,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
	DifficultyGT(EASY)
	HPLT(Player4,60)
	See(Player4)
	!StateCheck(Player4,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player4)  // Cloak of Mirroring
	!CheckStatGT(Player4,0,SANCTUARY)
	!CheckStatGT(Player4,0,DEATH_WARD)
	!CheckStatGT(Player4,1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player4,1,WIZARD_SPELL_TURNING)
	!CheckStatGT(Player4,0,WIZARD_SPELL_TRAP)
	!CheckStat(Player4,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player4,2,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Player4,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
	DifficultyGT(EASY)
	HPLT(Player5,60)
	See(Player5)
	!StateCheck(Player5,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player5)  // Cloak of Mirroring
	!CheckStatGT(Player5,0,SANCTUARY)
	!CheckStatGT(Player5,0,DEATH_WARD)
	!CheckStatGT(Player5,1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player5,1,WIZARD_SPELL_TURNING)
	!CheckStatGT(Player5,0,WIZARD_SPELL_TRAP)
	!CheckStat(Player5,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player5,2,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Player5,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
	DifficultyGT(EASY)
	HPLT(Player6,60)
	See(Player6)
	!StateCheck(Player6,STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",Player6)  // Cloak of Mirroring
	!CheckStatGT(Player6,0,SANCTUARY)
	!CheckStatGT(Player6,0,DEATH_WARD)
	!CheckStatGT(Player6,1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(Player6,1,WIZARD_SPELL_TURNING)
	!CheckStatGT(Player6,0,WIZARD_SPELL_TRAP)
	!CheckStat(Player6,1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(Player6,2,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Player6,50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
	DifficultyGT(EASY)
	OR(3)
		See([GOODCUTOFF])
		See(WeakestOf([GOODCUTOFF]))
		See(MostDamagedOf([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),9,LEVEL)
	HPLT(LastSeenBy(Myself),60)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
	DifficultyGT(EASY)
	See([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
	DifficultyGT(EASY)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
	DifficultyGT(EASY)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
	DifficultyGT(EASY)
	See(FourthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
	DifficultyGT(EASY)
	See(FifthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
	DifficultyGT(EASY)
	See(SixthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	!Difficulty(EASIEST)
	See([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	!Difficulty(EASIEST)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	!Difficulty(EASIEST)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	!Difficulty(EASIEST)
	See(FourthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	!Difficulty(EASIEST)
	See(FifthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	!Difficulty(EASIEST)
	See(SixthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	GlobalLT("OHN_MMIA","LOCALS",5)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	DifficultyGT(EASY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See([GOODCUTOFF])
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OHN_MMIA","LOCALS",1)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	GlobalLT("OHN_MMIA","LOCALS",5)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	DifficultyGT(EASY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OHN_MMIA","LOCALS",1)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	GlobalLT("OHN_MMIA","LOCALS",5)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	DifficultyGT(EASY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OHN_MMIA","LOCALS",1)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See([GOODCUTOFF])
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	GlobalLT("OHN_AAIA","LOCALS",3)
	See([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OHN_AAIA","LOCALS",1)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	GlobalLT("OHN_AAIA","LOCALS",3)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OHN_AAIA","LOCALS",1)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	!CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See([GOODCUTOFF.0.MIST.0.0.SUMMONED])
	HasItem("NISHRUU",LastSeenBy(Myself))  // Attack
	!StateCheck(Player1,STATE_DISABLED)
	!StateCheck(Player2,STATE_DISABLED)
	!StateCheck(Player3,STATE_DISABLED)
	!StateCheck(Player4,STATE_DISABLED)
	!StateCheck(Player5,STATE_DISABLED)
	!StateCheck(Player6,STATE_DISABLED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Malison","LOCALS")
	HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
	See([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),MALISON)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Malison","LOCALS",THREE_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Malison","LOCALS")
	HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),MALISON)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Malison","LOCALS",THREE_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Malison","LOCALS")
	HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),MALISON)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Malison","LOCALS",THREE_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Malison","LOCALS")
	HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
	See(FourthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),MALISON)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Malison","LOCALS",THREE_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Malison","LOCALS")
	HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
	See(FifthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),MALISON)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Malison","LOCALS",THREE_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Malison","LOCALS")
	HaveSpell(WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
	See(SixthNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckSpellState(LastSeenBy(Myself),MALISON)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Malison","LOCALS",THREE_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)  // SPWI412.SPL (Greater Malison)
END

IF
	Global("OH_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See([GOODCUTOFF])
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobal("OH_MSeq","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	Global("OH_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobal("OH_MSeq","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	Global("OH_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobal("OH_MSeq","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	Global("OH_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobal("OH_MSeq","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	Global("OH_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobal("OH_MSeq","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	Global("OH_MSeq","LOCALS",0)
	!Difficulty(EASIEST)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_IMMOBILE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobal("OH_MSeq","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Web","LOCALS",FOUR_ROUNDS)
		ApplySpellRES("OH_VSBL",Myself)  // No such index
		SetSequence(SEQ_CAST)
		DisplayString(Myself,8635)  // Minor Sequencer Activated
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHROMATIC_ORB)  // SPWI118.SPL (Chromatic Orb)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HaveSpell(WIZARD_WAIL_OF_THE_BANSHEE)  // SPWI913.SPL (Wail of the Banshee)
	!Difficulty(EASIEST)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),12)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_WAIL_OF_THE_BANSHEE)  // SPWI913.SPL (Wail of the Banshee)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HaveSpell(WIZARD_WAIL_OF_THE_BANSHEE)  // SPWI913.SPL (Wail of the Banshee)
	!Difficulty(EASIEST)
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),12)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_WAIL_OF_THE_BANSHEE)  // SPWI913.SPL (Wail of the Banshee)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HaveSpell(WIZARD_WAIL_OF_THE_BANSHEE)  // SPWI913.SPL (Wail of the Banshee)
	!Difficulty(EASIEST)
	See(ThirdNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),12)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_WAIL_OF_THE_BANSHEE)  // SPWI913.SPL (Wail of the Banshee)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HaveSpell(WIZARD_WAIL_OF_THE_BANSHEE)  // SPWI913.SPL (Wail of the Banshee)
	!Difficulty(EASIEST)
	See(FifthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),12)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_WAIL_OF_THE_BANSHEE)  // SPWI913.SPL (Wail of the Banshee)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HaveSpell(WIZARD_WAIL_OF_THE_BANSHEE)  // SPWI913.SPL (Wail of the Banshee)
	!Difficulty(EASIEST)
	See(SixthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),12)
	CheckStatGT(LastSeenBy(Myself),5,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_WAIL_OF_THE_BANSHEE)  // SPWI913.SPL (Wail of the Banshee)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
	!Difficulty(EASIEST)
	See(NearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
	!Difficulty(EASIEST)
	See(SecondNearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
	!Difficulty(EASIEST)
	See(ThirdNearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
	!Difficulty(EASIEST)
	See(FourthNearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
	!Difficulty(EASIEST)
	See(FifthNearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
	!Difficulty(EASIEST)
	See(SixthNearestEnemyOf(Myself))
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	OR(4)
		CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	OR(4)
		CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
	See(ThirdNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	OR(4)
		CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
	See(FourthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	OR(4)
		CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
	See(FifthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	OR(4)
		CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
	See(SixthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	OR(4)
		CheckStat(LastSeenBy(Myself),1,MINORGLOBE)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SPELL_THRUST)  // SPWI321.SPL (Spell Thrust)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_PierceW","LOCALS",6)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OH_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_PierceW","LOCALS",6)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OH_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_PierceW","LOCALS",6)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OH_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_PierceW","LOCALS",6)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OH_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_PierceW","LOCALS",6)
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OH_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_PierceW","LOCALS",6)
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_SHIELD_OF_THE_ARCHONS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		IncrementGlobal("OH_PierceW","LOCALS",1)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		ReallyForceSpell(LastSeenBy(Myself),WIZARD_PIERCE_MAGIC)  // SPWI608.SPL (Pierce Magic)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("SCRL9M",Myself)  // Spellstrike
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	See([PC.0.0.MAGE_ALL])
	OR(5)
		CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
		CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		DestroyItem("SCRL9M")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("SCRL9M",Myself)  // Spellstrike
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	OR(5)
		CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
		CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		DestroyItem("SCRL9M")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HasItem("SCRL9M",Myself)  // Spellstrike
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	See([PC])
	OR(5)
		CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
		CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
		CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		DestroyItem("SCRL9M")  // Spellstrike
		DisplayStringHead(Myself,46153)  // *uses a scroll*
		SpellNoDec(LastSeenBy(Myself),WIZARD_SPELL_STRIKE)  // SPWI903.SPL (Spellstrike)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
	See([PC.0.0.MAGE])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
	See(SecondNearest([PC.0.0.MAGE]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
	See([PC.0.0.BARD])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
	See(SecondNearest([PC.0.0.BARD]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
	See([PC.0.0.THIEF])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
	See(SecondNearest([PC.0.0.THIEF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
	See([PC.0.0.MAGE_THIEF])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
	See(SecondNearest([PC.0.0.MAGE_THIEF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),8,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)  // SPWI713.SPL (Finger of Death)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SLOW)  // SPWI312.SPL (Slow)
	See([GOODCUTOFF])
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +3
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // Firecam Full-Plate Armor
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SLOW)  // SPWI312.SPL (Slow)
	See(SecondNearest([GOODCUTOFF]))
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +3
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // Firecam Full-Plate Armor
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_SLOW)  // SPWI312.SPL (Slow)
	See(ThirdNearest([GOODCUTOFF]))
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +3
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquiped("NPPLAT",LastSeenBy(Myself))  // Firecam Full-Plate Armor
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_SLOW)  // SPWI312.SPL (Slow)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
	See([GOODCUTOFF])
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // The Equalizer
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // Psion's Blade +5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
	See(SecondNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // The Equalizer
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // Psion's Blade +5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
	See(ThirdNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // The Equalizer
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // Psion's Blade +5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
	See(FourthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // The Equalizer
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // Psion's Blade +5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
	See(FifthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // The Equalizer
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // Psion's Blade +5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
	See(SixthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("LEAT20",LastSeenBy(Myself))  // Aeger's Hide +3
	!HasItemEquiped("SHLD25",LastSeenBy(Myself))  // Shield of Harmony +2
	!HasItemEquipedReal("SW2H14",LastSeenBy(Myself))  // Lilarcor
	!HasItemEquipedReal("SW1H54",LastSeenBy(Myself))  // The Equalizer
	!HasItemEquipedReal("SW2H21",LastSeenBy(Myself))  // Psion's Blade +5
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CHAOS)  // SPWI508.SPL (Chaos)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_CDmg","LOCALS")
	HaveSpell(WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
	OR(2)
		!Range([EVILCUTOFF],15)
		CheckStatGT([EVILCUTOFF],90,RESISTPOISON)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquiped("AMUL22",LastSeenBy(Myself))  // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself))  // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself))  // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself))  // Albruin +1
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_CDmg","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_CDmg","LOCALS")
	HaveSpell(WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
	OR(2)
		!Range([EVILCUTOFF],15)
		CheckStatGT([EVILCUTOFF],90,RESISTPOISON)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquiped("AMUL22",LastSeenBy(Myself))  // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself))  // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself))  // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself))  // Albruin +1
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_CDmg","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_CDmg","LOCALS")
	HaveSpell(WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
	OR(2)
		!Range([EVILCUTOFF],15)
		CheckStatGT([EVILCUTOFF],90,RESISTPOISON)
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquiped("AMUL22",LastSeenBy(Myself))  // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself))  // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself))  // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself))  // Albruin +1
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_CDmg","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_CDmg","LOCALS")
	HaveSpell(WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
	OR(2)
		!Range([EVILCUTOFF],15)
		CheckStatGT([EVILCUTOFF],90,RESISTPOISON)
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquiped("AMUL22",LastSeenBy(Myself))  // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself))  // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself))  // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself))  // Albruin +1
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_CDmg","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_CDmg","LOCALS")
	HaveSpell(WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
	OR(2)
		!Range([EVILCUTOFF],15)
		CheckStatGT([EVILCUTOFF],90,RESISTPOISON)
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquiped("AMUL22",LastSeenBy(Myself))  // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself))  // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself))  // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself))  // Albruin +1
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_CDmg","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_CDmg","LOCALS")
	HaveSpell(WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
	OR(2)
		!Range([EVILCUTOFF],15)
		CheckStatGT([EVILCUTOFF],90,RESISTPOISON)
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	!Class(LastSeenBy(Myself),MONK)
	!Class(LastSeenBy(Myself),DRUID_ALL)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	!HasItemEquiped("AMUL22",LastSeenBy(Myself))  // Periapt of Proof Against Poison
	!HasItemEquiped("HELM30",LastSeenBy(Myself))  // Thieves' Hood
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!HasItemEquiped("RING46",LastSeenBy(Myself))  // Ring of Anti-Venom
	!HasItemEquipedReal("SW1H34",LastSeenBy(Myself))  // Albruin +1
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_CDmg","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
	OR(4)
		Range([GOODCUTOFF.0.0.MAGE_ALL],30)
		Range([GOODCUTOFF.0.0.BARD_ALL],30)
		Range([GOODCUTOFF.0.0.CLERIC_ALL],30)
		Range([GOODCUTOFF.0.0.DRUID_ALL],30)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!StateCheck(Myself,STATE_SILENCED)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_SUMMON_HAKEASHAR)  // SPWI719.SPL (Summon Hakeashar)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See([GOODCUTOFF])
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See([PC.0.0.MAGE])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC.0.0.MAGE]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See([PC.0.0.MAGE_THIEF])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC.0.0.MAGE_THIEF]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See([PC.0.0.BARD])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([PC.0.0.BARD]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_BreachW","LOCALS",6)
	!GlobalTimerNotExpired("OH_BREACH","LOCALS")
	See([PC])
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("OH_BreachW","LOCALS",1)
		SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	!GlobalTimerNotExpired("OH_BREACH","LOCALS")
	GlobalLT("OH_BreachW","LOCALS",6)
	See(SecondNearest([PC]))
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("OH_BreachW","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!GlobalTimerNotExpired("OH_BREACH","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_BreachW","LOCALS",6)
	See(ThirdNearest([PC]))
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("OH_BreachW","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!GlobalTimerNotExpired("OH_BREACH","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_BreachW","LOCALS",6)
	See(FourthNearest([PC]))
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("OH_BreachW","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!GlobalTimerNotExpired("OH_BREACH","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_BreachW","LOCALS",6)
	See(FifthNearest([PC]))
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("OH_BreachW","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!GlobalTimerNotExpired("OH_BREACH","LOCALS")
	HasItem("WAND18",Myself)  // Wand of Spell Striking
	GlobalLT("OH_BreachW","LOCALS",6)
	See(SixthNearest([PC]))
	OR(4)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		IncrementGlobal("OH_BreachW","LOCALS",1)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,31971)  // *uses a wand*
		UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	See([GOODCUTOFF])
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	HaveSpell(WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	HaveSpell(WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
	HaveSpell(WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Scld","LOCALS")
	HaveSpell(WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
	See([GOODCUTOFF])
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!HasItemEquiped("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Scld","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Scld","LOCALS")
	HaveSpell(WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
	See(SecondNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!HasItemEquiped("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Scld","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Scld","LOCALS")
	HaveSpell(WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
	See(ThirdNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!HasItemEquiped("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Scld","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Scld","LOCALS")
	HaveSpell(WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
	See(FourthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!HasItemEquiped("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Scld","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Scld","LOCALS")
	HaveSpell(WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
	See(FifthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!HasItemEquiped("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Scld","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_Scld","LOCALS")
	HaveSpell(WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
	See(SixthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	CheckStatGT(LastSeenBy(Myself),2,SAVEVSDEATH)
	!HasItemEquiped("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Scld","LOCALS",TWO_ROUNDS)
		Spell(LastSeenBy(Myself),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
	CheckStat(Myself,0,WIZARD_FIRE_SHIELD)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
	See(ThirdNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
	See(FourthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
	See(FifthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
	See(SixthNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)  // SPWI314.SPL (Vampiric Touch)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_HORROR)  // SPWI205.SPL (Horror)
	See([GOODCUTOFF])
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!Kit(LastSeenBy(Myself),Blackguard)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("CLCK30",LastSeenBy(Myself))  // Cloak of Bravery
	!HasItemEquipedReal("SW1H32",LastSeenBy(Myself))  // Peridan +2
	!HasItemEquipedReal("MISCBC",LastSeenBy(Myself))  // Blackrazor +3
	!HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_HORROR)  // SPWI205.SPL (Horror)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_HORROR)  // SPWI205.SPL (Horror)
	See(SecondNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!Kit(LastSeenBy(Myself),Blackguard)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("CLCK30",LastSeenBy(Myself))  // Cloak of Bravery
	!HasItemEquipedReal("SW1H32",LastSeenBy(Myself))  // Peridan +2
	!HasItemEquipedReal("MISCBC",LastSeenBy(Myself))  // Blackrazor +3
	!HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_HORROR)  // SPWI205.SPL (Horror)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_HORROR)  // SPWI205.SPL (Horror)
	See(ThirdNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!Kit(LastSeenBy(Myself),Blackguard)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("CLCK30",LastSeenBy(Myself))  // Cloak of Bravery
	!HasItemEquipedReal("SW1H32",LastSeenBy(Myself))  // Peridan +2
	!HasItemEquipedReal("MISCBC",LastSeenBy(Myself))  // Blackrazor +3
	!HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_HORROR)  // SPWI205.SPL (Horror)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_HORROR)  // SPWI205.SPL (Horror)
	See(FourthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!Kit(LastSeenBy(Myself),Blackguard)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("CLCK30",LastSeenBy(Myself))  // Cloak of Bravery
	!HasItemEquipedReal("SW1H32",LastSeenBy(Myself))  // Peridan +2
	!HasItemEquipedReal("MISCBC",LastSeenBy(Myself))  // Blackrazor +3
	!HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_HORROR)  // SPWI205.SPL (Horror)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_HORROR)  // SPWI205.SPL (Horror)
	See(FifthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!Kit(LastSeenBy(Myself),Blackguard)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("CLCK30",LastSeenBy(Myself))  // Cloak of Bravery
	!HasItemEquipedReal("SW1H32",LastSeenBy(Myself))  // Peridan +2
	!HasItemEquipedReal("MISCBC",LastSeenBy(Myself))  // Blackrazor +3
	!HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_HORROR)  // SPWI205.SPL (Horror)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_HORROR)  // SPWI205.SPL (Horror)
	See(SixthNearest([GOODCUTOFF]))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Kit(LastSeenBy(Myself),CAVALIER)
	!Kit(LastSeenBy(Myself),Blackguard)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_DISABLED)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("CLCK30",LastSeenBy(Myself))  // Cloak of Bravery
	!HasItemEquipedReal("SW1H32",LastSeenBy(Myself))  // Peridan +2
	!HasItemEquipedReal("MISCBC",LastSeenBy(Myself))  // Blackrazor +3
	!HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_HORROR)  // SPWI205.SPL (Horror)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	HaveSpell(WIZARD_ANIMATE_DEAD)  // SPWI501.SPL (Animate Dead)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	Range([GOODCUTOFF],30)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(Myself,WIZARD_ANIMATE_DEAD)  // SPWI501.SPL (Animate Dead)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_CONTAGION)  // SPWI409.SPL (Contagion)
	See([GOODCUTOFF.0.0.FIGHTER_ALL])
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CONTAGION)  // SPWI409.SPL (Contagion)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_CONTAGION)  // SPWI409.SPL (Contagion)
	See(SecondNearest([GOODCUTOFF.0.0.FIGHTER_ALL]))
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CONTAGION)  // SPWI409.SPL (Contagion)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_CONTAGION)  // SPWI409.SPL (Contagion)
	See([GOODCUTOFF.0.0.RANGER_ALL])
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CONTAGION)  // SPWI409.SPL (Contagion)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_CONTAGION)  // SPWI409.SPL (Contagion)
	See(SecondNearest([GOODCUTOFF.0.0.RANGER_ALL]))
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CONTAGION)  // SPWI409.SPL (Contagion)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(WIZARD_CONTAGION)  // SPWI409.SPL (Contagion)
	See([GOODCUTOFF])
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatLT(LastSeenBy(Myself),100,RESISTPOISON)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_CONTAGION)  // SPWI409.SPL (Contagion)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	OR(4)
		See([GOODCUTOFF.0.0.BARD_ALL])
		See([GOODCUTOFF.0.0.DRUID_ALL])
		See([GOODCUTOFF.0.0.CLERIC_ALL])
		See([GOODCUTOFF.0.0.MAGE_ALL])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	See([GOODCUTOFF])
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	See(SecondNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
	See(ThirdNearest([GOODCUTOFF]))
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	OR(4)
		See([GOODCUTOFF.0.0.BARD_ALL])
		See([GOODCUTOFF.0.0.DRUID_ALL])
		See([GOODCUTOFF.0.0.CLERIC_ALL])
		See([GOODCUTOFF.0.0.MAGE_ALL])
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See([GOODCUTOFF])
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(SecondNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(ThirdNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(FourthNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(FifthNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
	CheckStatLT(Myself,50,SPELLFAILUREMAGE)
	!CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
	!StateCheck(Myself,STATE_SILENCED)
	See(SixthNearest([GOODCUTOFF]))
	!HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
	!HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)  // SPWI119.SPL (Larloch's Minor Drain)
	See([GOODCUTOFF])
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)  // SPWI119.SPL (Larloch's Minor Drain)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)  // SPWI119.SPL (Larloch's Minor Drain)
	See(SecondNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)  // SPWI119.SPL (Larloch's Minor Drain)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)  // SPWI119.SPL (Larloch's Minor Drain)
	See(ThirdNearest([GOODCUTOFF]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),GOLEM)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	CheckStatLT(LastSeenBy(Myself),55,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)  // SPWI119.SPL (Larloch's Minor Drain)
END

IF
	Allegiance(Myself,EVILCUTOFF)
	!AreaType(OUTDOOR)
	!Range(NearestEnemyOf(Myself),30)
	Range(NearestDoor,15)
	OpenState(NearestDoor,FALSE)
THEN
	RESPONSE #100
		MoveToObject(NearestDoor)
		OpenDoor(NearestDoor)
END

IF
	Global("OH_Active","LOCALS",1)
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	!StateCheck(Myself,STATE_BLIND)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	OR(3)
		RandomNum(5,1)
		CombatCounter(0)
		GlobalTimerNotExpired("OH_TStop","LOCALS")
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Global("OH_Active","LOCALS",1)
	!See([GOODCUTOFF])
	RandomNum(2,1)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	!CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(3)
		HitBy([GOODCUTOFF],CRUSHING)
		HitBy([GOODCUTOFF],PIERCING)
		HitBy([GOODCUTOFF],SLASHING)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	!GlobalTimerNotExpired("OH_TStop","LOCALS")
	GlobalTimerNotExpired("OH_Cast","LOCALS")
	Range([GOODCUTOFF],4)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

