IF
    Global("OH_Active","LOCALS",0)
    OR(3)
        See(NearestEnemyOf(Myself))
        AttackedBy([ANYONE],DEFAULT)
        TookDamage()
THEN
    RESPONSE #100
        SetGlobal("OH_Active","LOCALS",1)
        SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
        Enemy()
        Shout(ASSIST)
        Continue()
END

IF
    Global("OH_Active","LOCALS",0)
    Heard([EVILCUTOFF],ASSIST)
    Range(LastHeardBy(Myself),25)
THEN
    RESPONSE #100
        SetGlobal("OH_Active","LOCALS",1)
        SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
        Enemy()
        Shout(ASSIST)
        MoveToObject(LastHeardBy(Myself))
END

IF
    Global("OH_Active","LOCALS",1)
    Global("OH_CHCntg","LOCALS",0)
    LevelGT(Myself,17)
THEN
    RESPONSE #100
        SetGlobal("OH_CHCntg","LOCALS",1)
        DisplayString(Myself,26328)  // Chain Contingency
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements)
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)  // SPWI803.SPL (Protection From Energy)
        ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
        Continue()
END

IF
    Global("OH_Active","LOCALS",1)
    Global("OH_Cntg","LOCALS",0)
    LevelGT(Myself,11)
    HPPercentLT(Myself,51)
    !StateCheck(Myself,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetGlobal("OH_Cntg","LOCALS",1)
        DisplayString(Myself,8292)  // Contingency Active
        ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY)  // SPWI405.SPL (Improved Invisibility)
        Continue()
END

IF
    OR(5)
        Global("OH_Active","LOCALS",0)
        !Allegiance(Myself,EVILCUTOFF)
        StateCheck(Myself,STATE_IMMOBILE)
        StateCheck(Myself,STATE_PANIC)
        StateCheck(Myself,STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        NoAction()
END

IF
    !GlobalTimerNotExpired("OH_Rest","LOCALS")
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
        SetGlobal("OH_CHCntg","LOCALS",0)
        SetGlobal("OH_Cntg","LOCALS",0)
        SetGlobal("OH_Seq","LOCALS",0)
        SetGlobal("OH_MSeq","LOCALS",0)
        SetGlobal("OH_Trig","LOCALS",0)
        ApplySpell(Myself,RESTORE_FULL_HEALTH)  // SPIN746.SPL (No such index)
        Rest()
END

IF
    !GlobalTimerNotExpired("OH_TStop","LOCALS")
    Global("OH_Msld","LOCALS",0)
    Detect([EVILCUTOFF.0.0.0.0.ILLUSIONARY])
    CheckStat(LastSeenBy(Myself),1,PUPPETMASTERTYPE)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobal("OH_Msld","LOCALS",1)
        ActionOverride(LastSeenBy(Myself),ChangeAIScript("OHBMSLD",OVERRIDE))
        SetInterrupt(TRUE)
END

IF
    Global("OH_Heal","LOCALS",1)
    OR(2)
        HPPercentGT(Myself,84)
        !HasItem("POTN52",Myself)  // Potion of Extra Healing
THEN
    RESPONSE #100
        SetGlobal("OH_Heal","LOCALS",0)
END

IF
    HPPercentLT(Myself,85)
    Global("OH_Heal","LOCALS",0)
    HasItem("POTN52",Myself)  // Potion of Extra Healing
THEN
    RESPONSE #100
        SetGlobal("OH_Heal","LOCALS",1)
END

IF
    Global("OH_Heal","LOCALS",1)
    !StateCheck(Myself,STATE_INVISIBLE)
    !Global("dvgldust","LOCALS",1)
    HasItem("POTN10",Myself)  // Potion of Invisibility
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !CheckStatGT(Player1,0,TRUE_SIGHT)
    !CheckStatGT(Player2,0,TRUE_SIGHT)
    !CheckStatGT(Player3,0,TRUE_SIGHT)
    !CheckStatGT(Player4,0,TRUE_SIGHT)
    !CheckStatGT(Player5,0,TRUE_SIGHT)
    !CheckStatGT(Player6,0,TRUE_SIGHT)
    !CheckStatGT([GOODCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
    !CheckStatGT([GOODCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
    !CheckStat(Myself,1,PUPPETTYPE)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        UseItem("POTN10",Myself)  // Potion of Invisibility
        DisplayStringHead(Myself,46150)  // *quaffs a potion*
END

IF
    Global("OH_Heal","LOCALS",1)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    HasItem("POTN52",Myself)  // Potion of Extra Healing
    HPPercentLT(Myself,85)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        UseItem("POTN52",Myself)  // Potion of Extra Healing
        DisplayStringHead(Myself,46150)  // *quaffs a potion*
END

IF
    StateCheck(Myself,STATE_SILENCED)
    HaveSpell(WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    Global("OH_Trig","LOCALS",0)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !StateCheck(Myself,STATE_SILENCED)
    !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    Range([GOODCUTOFF],30)
    LevelGT(Myself,15)
THEN
    RESPONSE #100
        SetGlobal("OH_Trig","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        DisplayString(Myself,26243)  // Spell Trigger
        ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
        ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
        ReallyForceSpell(Myself,WIZARD_TRUE_SIGHT)  // SPWI609.SPL (True Sight)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    CheckStatLT(Myself,1,STONESKINS)
    !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    Global("OH_Seq","LOCALS",0)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !StateCheck(Myself,STATE_SILENCED)
    LevelGT(Myself,13)
THEN
    RESPONSE #100
        SetGlobal("OH_Seq","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        DisplayString(Myself,39969)  // Spell Sequencer—Fired
        ReallyForceSpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
        ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
        ReallyForceSpell(Myself,WIZARD_MINOR_SPELL_DEFLECTION)  // SPWI318.SPL (Minor Spell Deflection)
END

IF
    CheckStatLT(Myself,1,STONESKINS)
    !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    !StateCheck(Myself,STATE_INVISIBLE)
    !Global("dvgldust","LOCALS",1)
    HasItem("POTN10",Myself)  // Potion of Invisibility
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !CheckStatGT(Player1,0,TRUE_SIGHT)
    !CheckStatGT(Player2,0,TRUE_SIGHT)
    !CheckStatGT(Player3,0,TRUE_SIGHT)
    !CheckStatGT(Player4,0,TRUE_SIGHT)
    !CheckStatGT(Player5,0,TRUE_SIGHT)
    !CheckStatGT(Player6,0,TRUE_SIGHT)
    !CheckStatGT([GOODCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
    !CheckStatGT([GOODCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
    !CheckStat(Myself,1,PUPPETTYPE)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        UseItem("POTN10",Myself)  // Potion of Invisibility
        DisplayStringHead(Myself,46150)  // *quaffs a potion*
        SetInterrupt(TRUE)
END

IF
    !AreaCheck("OH8000")  // TBP2 - Suzail Tavern
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !GlobalTimerNotExpired("OH_TStop","LOCALS")
    !CheckStatGT(Myself,0,AURACLEANSING)
    Range([GOODCUTOFF],30)
    HaveSpell(WIZARD_TIME_STOP)  // SPWI909.SPL (Time Stop)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_TStop","LOCALS",THREE_ROUNDS)
        Spell(Myself,WIZARD_TIME_STOP)  // SPWI909.SPL (Time Stop)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    HaveSpell(WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (Improved Alacrity)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    Range([GOODCUTOFF],30)
    DifficultyGT(EASY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (Improved Alacrity)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    Range([GOODCUTOFF],30)
    OR(3)
        CheckStatLT(Myself,1,STONESKINS)
        AttackedBy([ANYONE],DEFAULT)
        Range([GOODCUTOFF],4)
    !CheckStat(Myself,1,PUPPETTYPE)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    CheckStatLT(Myself,1,STONESKINS)
    HaveSpell(WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    !StateCheck(Myself,STATE_MIRRORIMAGE)
    HaveSpell(WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
    !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    !CheckStatGT(Player1,0,TRUE_SIGHT)
    !CheckStatGT(Player2,0,TRUE_SIGHT)
    !CheckStatGT(Player3,0,TRUE_SIGHT)
    !CheckStatGT(Player4,0,TRUE_SIGHT)
    !CheckStatGT(Player5,0,TRUE_SIGHT)
    !CheckStatGT(Player6,0,TRUE_SIGHT)
    !CheckStatGT([GOODCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
    !CheckStatGT([GOODCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_MIRROR_IMAGE)  // SPWI212.SPL (Mirror Image)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    HaveSpell(WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See([GOODCUTOFF.0.MIST.0.0.SUMMONED])
    HasItem("NISHRUU",LastSeenBy(Myself))  // Attack
    !StateCheck(Player1,STATE_DISABLED)
    !StateCheck(Player2,STATE_DISABLED)
    !StateCheck(Player3,STATE_DISABLED)
    !StateCheck(Player4,STATE_DISABLED)
    !StateCheck(Player5,STATE_DISABLED)
    !StateCheck(Player6,STATE_DISABLED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)  // SPWI302.SPL (Remove Magic)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
    OR(3)
        See([GOODCUTOFF.0.0.0.0.SUMMONED])
        See([GOODCUTOFF.WEAPON.SWORD.0.0.SUMMONED])
        See([GOODCUTOFF.0.MIST.0.0.SUMMONED])
    OR(3)
        HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
        HasItem("NISHRUU",LastSeenBy(Myself))  // Attack
        NumCreatureGT([GOODCUTOFF.0.0.0.0.SUMMONED],2)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)  // SPWI605.SPL (Death Spell)
        SetInterrupt(TRUE)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    Global("OH_MSeq","LOCALS",0)
    See([GOODCUTOFF.0.0.0.0.SUMMONED])
    HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobal("OH_MSeq","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetSequence(SEQ_CAST)
        DisplayString(Myself,8635)  // Minor Sequencer Activated
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    See([GOODCUTOFF.0.0.0.0.SUMMONED])
    HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
    DifficultyGT(EASY)
    HPLT(Player1,60)
    See(Player1)
    !StateCheck(Player1,STATE_REALLY_DEAD)
    !HasItemEquiped("CLCK26",Player1)  // Cloak of Mirroring
    !CheckStatGT(Player1,0,SANCTUARY)
    !CheckStatGT(Player1,0,DEATH_WARD)
    !CheckStatGT(Player1,1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player1,1,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player1,0,WIZARD_SPELL_TRAP)
    !CheckStat(Player1,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(Player1,2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
    CheckStatLT(Player1,50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Player1,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
    DifficultyGT(EASY)
    HPLT(Player2,60)
    See(Player2)
    !StateCheck(Player2,STATE_REALLY_DEAD)
    !HasItemEquiped("CLCK26",Player2)  // Cloak of Mirroring
    !CheckStatGT(Player2,0,SANCTUARY)
    !CheckStatGT(Player2,0,DEATH_WARD)
    !CheckStatGT(Player2,1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player2,1,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player2,0,WIZARD_SPELL_TRAP)
    !CheckStat(Player2,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(Player2,2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
    CheckStatLT(Player2,50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Player2,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
    DifficultyGT(EASY)
    HPLT(Player3,60)
    See(Player3)
    !StateCheck(Player3,STATE_REALLY_DEAD)
    !HasItemEquiped("CLCK26",Player3)  // Cloak of Mirroring
    !CheckStatGT(Player3,0,SANCTUARY)
    !CheckStatGT(Player3,0,DEATH_WARD)
    !CheckStatGT(Player3,1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player3,1,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player3,0,WIZARD_SPELL_TRAP)
    !CheckStat(Player3,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(Player3,2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
    CheckStatLT(Player3,50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Player3,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
    DifficultyGT(EASY)
    HPLT(Player4,60)
    See(Player4)
    !StateCheck(Player4,STATE_REALLY_DEAD)
    !HasItemEquiped("CLCK26",Player4)  // Cloak of Mirroring
    !CheckStatGT(Player4,0,SANCTUARY)
    !CheckStatGT(Player4,0,DEATH_WARD)
    !CheckStatGT(Player4,1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player4,1,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player4,0,WIZARD_SPELL_TRAP)
    !CheckStat(Player4,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(Player4,2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
    CheckStatLT(Player4,50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Player4,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
    DifficultyGT(EASY)
    HPLT(Player5,60)
    See(Player5)
    !StateCheck(Player5,STATE_REALLY_DEAD)
    !HasItemEquiped("CLCK26",Player5)  // Cloak of Mirroring
    !CheckStatGT(Player5,0,SANCTUARY)
    !CheckStatGT(Player5,0,DEATH_WARD)
    !CheckStatGT(Player5,1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player5,1,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player5,0,WIZARD_SPELL_TRAP)
    !CheckStat(Player5,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(Player5,2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
    CheckStatLT(Player5,50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Player5,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
    DifficultyGT(EASY)
    HPLT(Player6,60)
    See(Player6)
    !StateCheck(Player6,STATE_REALLY_DEAD)
    !HasItemEquiped("CLCK26",Player6)  // Cloak of Mirroring
    !CheckStatGT(Player6,0,SANCTUARY)
    !CheckStatGT(Player6,0,DEATH_WARD)
    !CheckStatGT(Player6,1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player6,1,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player6,0,WIZARD_SPELL_TRAP)
    !CheckStat(Player6,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(Player6,2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
    CheckStatLT(Player6,50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Player6,WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
    DifficultyGT(EASY)
    OR(3)
        See([GOODCUTOFF])
        See(WeakestOf([GOODCUTOFF]))
        See(MostDamagedOf([GOODCUTOFF]))
    CheckStatGT(LastSeenBy(Myself),9,LEVEL)
    HPLT(LastSeenBy(Myself),60)
    !StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
    !CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H71",LastSeenBy(Myself))  // Hindo's Doom +4
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_KILL)  // SPWI912.SPL (Power Word, Kill)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    DifficultyGT(EASY)
    See([GOODCUTOFF])
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    DifficultyGT(EASY)
    See(SecondNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    DifficultyGT(EASY)
    See(ThirdNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    DifficultyGT(EASY)
    See(FourthNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    DifficultyGT(EASY)
    See(FifthNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
    DifficultyGT(EASY)
    See(SixthNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        Spell(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)  // SPWI922.SPL (Dragon's Breath)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
    !Difficulty(EASIEST)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    HPLT(Player1,90)
    See(Player1)
    !StateCheck(Player1,STATE_REALLY_DEAD)
    !StateCheck(Player1,STATE_NOT_TARGETABLE)
    !StateCheck(Player1,STATE_HARMLESS)
    !CheckStatGT(Player1,0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player1,0,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player1,0,WIZARD_SPELL_TRAP)
    !CheckStatGT(Player1,0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(Player1,0,CLERIC_FREE_ACTION)
    !CheckStat(Player1,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(Player1,2,WIZARD_SPELL_IMMUNITY)
    !CheckStat(Player1,1,OFFENSIVE_MODIFIER)
    !HasItemEquipedReal("NPSW01",Player1)  // Sword of Arvoreen +3
    !HasItemEquipedReal("SW1H27",Player1)  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",Player1)  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",Player1)  // Spider's Bane +2
    CheckStatLT(Player1,50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(Player1,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
    !Difficulty(EASIEST)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    HPLT(Player2,90)
    See(Player2)
    !StateCheck(Player2,STATE_REALLY_DEAD)
    !StateCheck(Player2,STATE_NOT_TARGETABLE)
    !StateCheck(Player2,STATE_HARMLESS)
    !CheckStatGT(Player2,0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player2,0,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player2,0,WIZARD_SPELL_TRAP)
    !CheckStatGT(Player2,0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(Player2,0,CLERIC_FREE_ACTION)
    !CheckStat(Player2,2,WIZARD_SPELL_IMMUNITY)
    !CheckStat(Player2,1,OFFENSIVE_MODIFIER)
    !CheckStat(Player2,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquipedReal("NPSW01",Player2)  // Sword of Arvoreen +3
    !HasItemEquipedReal("SW1H27",Player2)  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",Player2)  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",Player2)  // Spider's Bane +2
    CheckStatLT(Player2,50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(Player2,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
    !Difficulty(EASIEST)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    HPLT(Player3,90)
    See(Player3)
    !StateCheck(Player3,STATE_REALLY_DEAD)
    !StateCheck(Player3,STATE_NOT_TARGETABLE)
    !StateCheck(Player3,STATE_HARMLESS)
    !CheckStatGT(Player3,0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player3,0,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player3,0,WIZARD_SPELL_TRAP)
    !CheckStatGT(Player3,0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(Player3,0,CLERIC_FREE_ACTION)
    !CheckStat(Player3,2,WIZARD_SPELL_IMMUNITY)
    !CheckStat(Player3,1,OFFENSIVE_MODIFIER)
    !CheckStat(Player3,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquipedReal("NPSW01",Player3)  // Sword of Arvoreen +3
    !HasItemEquipedReal("SW1H27",Player3)  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",Player3)  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",Player3)  // Spider's Bane +2
    CheckStatLT(Player3,50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(Player3,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
    !Difficulty(EASIEST)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    HPLT(Player4,90)
    See(Player4)
    !StateCheck(Player4,STATE_REALLY_DEAD)
    !StateCheck(Player4,STATE_NOT_TARGETABLE)
    !StateCheck(Player4,STATE_HARMLESS)
    !CheckStatGT(Player4,0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player4,0,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player4,0,WIZARD_SPELL_TRAP)
    !CheckStatGT(Player4,0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(Player4,0,CLERIC_FREE_ACTION)
    !CheckStat(Player4,2,WIZARD_SPELL_IMMUNITY)
    !CheckStat(Player4,1,OFFENSIVE_MODIFIER)
    !CheckStat(Player4,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquipedReal("NPSW01",Player4)  // Sword of Arvoreen +3
    !HasItemEquipedReal("SW1H27",Player4)  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",Player4)  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",Player4)  // Spider's Bane +2
    CheckStatLT(Player4,50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(Player4,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
    !Difficulty(EASIEST)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    HPLT(Player5,90)
    See(Player5)
    !StateCheck(Player5,STATE_REALLY_DEAD)
    !StateCheck(Player5,STATE_NOT_TARGETABLE)
    !StateCheck(Player5,STATE_HARMLESS)
    !CheckStatGT(Player5,0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player5,0,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player5,0,WIZARD_SPELL_TRAP)
    !CheckStatGT(Player5,0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(Player5,0,CLERIC_FREE_ACTION)
    !CheckStat(Player5,2,WIZARD_SPELL_IMMUNITY)
    !CheckStat(Player5,1,OFFENSIVE_MODIFIER)
    !CheckStat(Player5,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquipedReal("NPSW01",Player5)  // Sword of Arvoreen +3
    !HasItemEquipedReal("SW1H27",Player5)  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",Player5)  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",Player5)  // Spider's Bane +2
    CheckStatLT(Player5,50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(Player5,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
    !Difficulty(EASIEST)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    HPLT(Player6,90)
    See(Player6)
    !StateCheck(Player6,STATE_REALLY_DEAD)
    !StateCheck(Player6,STATE_NOT_TARGETABLE)
    !StateCheck(Player6,STATE_HARMLESS)
    !CheckStatGT(Player6,0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(Player6,0,WIZARD_SPELL_TURNING)
    !CheckStatGT(Player6,0,WIZARD_SPELL_TRAP)
    !CheckStatGT(Player6,0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(Player6,0,CLERIC_FREE_ACTION)
    !CheckStat(Player6,2,WIZARD_SPELL_IMMUNITY)
    !CheckStat(Player6,1,OFFENSIVE_MODIFIER)
    !CheckStat(Player6,1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquipedReal("NPSW01",Player6)  // Sword of Arvoreen +3
    !HasItemEquipedReal("SW1H27",Player6)  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",Player6)  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",Player6)  // Spider's Bane +2
    CheckStatLT(Player6,50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(Player6,WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
    !Difficulty(EASIEST)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See([GOODCUTOFF])
    HPLT(LastSeenBy(Myself),90)
    !General(LastSeenBy(Myself),UNDEAD)
    !Race(LastSeenBy(Myself),DEMONIC)
    CheckStatGT(LastSeenBy(Myself),9,LEVEL)
    !StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
    !HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
    !HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +3
    !HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)  // SPWI715.SPL (Power Word, Stun)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See([PC.0.0.PALADIN_ALL])
    Kit(LastSeenBy(Myself),INQUISITOR)
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See([PC.0.0.MAGE_ALL])
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See(SecondNearest([PC.0.0.MAGE_ALL]))
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See(ThirdNearest([PC.0.0.MAGE_ALL]))
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See([PC.0.0.DRUID_ALL])
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See(SecondNearest([PC.0.0.DRUID_ALL]))
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See(ThirdNearest([PC.0.0.DRUID_ALL]))
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See([PC.0.0.CLERIC_ALL])
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See(SecondNearest([PC.0.0.CLERIC_ALL]))
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See(ThirdNearest([PC.0.0.CLERIC_ALL]))
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See([PC.0.0.BARD_ALL])
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    OR(2)
        CheckStatGT(Myself,0,AURACLEANSING)
        !GlobalTimerNotExpired("OH_PWR","LOCALS")
    HaveSpell(WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
    !Difficulty(EASIEST)
    See(SecondNearest([PC.0.0.BARD_ALL]))
    !StateCheck(LastSeenBy(Myself),STATE_SILENCED)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    !HasItemEquiped("AMUL21",LastSeenBy(Myself))  // Amulet of Power
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_PWR","LOCALS",TWO_ROUNDS)
        Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_SILENCE)  // SPWI612.SPL (Power Word, Silence)
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
    HaveSpell(WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
    !CheckStatGT(Player1,0,TRUE_SIGHT)
    !CheckStatGT(Player2,0,TRUE_SIGHT)
    !CheckStatGT(Player3,0,TRUE_SIGHT)
    !CheckStatGT(Player4,0,TRUE_SIGHT)
    !CheckStatGT(Player5,0,TRUE_SIGHT)
    !CheckStatGT(Player6,0,TRUE_SIGHT)
    !CheckStatGT([GOODCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
    !CheckStatGT([GOODCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    !CheckStat(Myself,1,PUPPETTYPE)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_SHADOW_DOOR)  // SPWI505.SPL (Shadow Door)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    GlobalLT("OHN_MMIA","LOCALS",5)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    DifficultyGT(EASY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See([GOODCUTOFF])
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("OHN_MMIA","LOCALS",1)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    GlobalLT("OHN_MMIA","LOCALS",5)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    DifficultyGT(EASY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(SecondNearest([GOODCUTOFF]))
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("OHN_MMIA","LOCALS",1)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    GlobalLT("OHN_MMIA","LOCALS",5)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    DifficultyGT(EASY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(ThirdNearest([GOODCUTOFF]))
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("OHN_MMIA","LOCALS",1)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See([GOODCUTOFF])
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(SecondNearest([GOODCUTOFF]))
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(ThirdNearest([GOODCUTOFF]))
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
    GlobalLT("OHN_AAIA","LOCALS",3)
    See([GOODCUTOFF])
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("OHN_AAIA","LOCALS",1)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
    GlobalLT("OHN_AAIA","LOCALS",3)
    See(SecondNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("OHN_AAIA","LOCALS",1)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
    GlobalLT("OHN_AAIA","LOCALS",3)
    See(ThirdNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("OHN_AAIA","LOCALS",1)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    GlobalLT("OHN_AAFA","LOCALS",3)
    HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
    See([GOODCUTOFF])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("OHN_AAFA","LOCALS",1)
        Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    GlobalLT("OHN_AAFA","LOCALS",3)
    HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
    See(SecondNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("OHN_AAFA","LOCALS",1)
        Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
    CheckStatGT(Myself,0,AURACLEANSING)
    GlobalLT("OHN_AAFA","LOCALS",3)
    HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
    See(ThirdNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        IncrementGlobal("OHN_AAFA","LOCALS",1)
        Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    !Difficulty(EASIEST)
    See(NearestEnemyOf(Myself))
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    !Difficulty(EASIEST)
    See(SecondNearestEnemyOf(Myself))
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    !Difficulty(EASIEST)
    See(ThirdNearestEnemyOf(Myself))
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    !Difficulty(EASIEST)
    See(FourthNearestEnemyOf(Myself))
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    !Difficulty(EASIEST)
    See(FifthNearestEnemyOf(Myself))
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
    !Difficulty(EASIEST)
    See(SixthNearestEnemyOf(Myself))
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)  // SPWI812.SPL (Abi-Dalzim's Horrid Wilting)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
    !CheckStatGT(Myself,0,WIZARD_SPELL_TURNING)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_SPELL_TURNING)  // SPWI701.SPL (Spell Turning)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_SoC","LOCALS")
    HaveSpell(WIZARD_SPHERE_OF_CHAOS)  // SPWI711.SPL (Sphere of Chaos)
    Range([GOODCUTOFF],15)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_SoC","LOCALS",FIVE_ROUNDS)
        Spell(Myself,WIZARD_SPHERE_OF_CHAOS)  // SPWI711.SPL (Sphere of Chaos)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !GlobalTimerNotExpired("OH_TStop","LOCALS")
    HasItem("WAND18",Myself)  // Wand of Spell Striking
    GlobalLT("OH_BreachW","LOCALS",6)
    !GlobalTimerNotExpired("OH_BREACH","LOCALS")
    See([PC])
    OR(4)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
    !StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        IncrementGlobal("OH_BreachW","LOCALS",1)
        SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        DisplayStringHead(Myself,31971)  // *uses a wand*
        UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
        SetInterrupt(TRUE)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !GlobalTimerNotExpired("OH_TStop","LOCALS")
    HasItem("WAND18",Myself)  // Wand of Spell Striking
    !GlobalTimerNotExpired("OH_BREACH","LOCALS")
    GlobalLT("OH_BreachW","LOCALS",6)
    See(SecondNearest([PC]))
    OR(4)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
    !StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        IncrementGlobal("OH_BreachW","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
        DisplayStringHead(Myself,31971)  // *uses a wand*
        UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
        SetInterrupt(TRUE)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !GlobalTimerNotExpired("OH_TStop","LOCALS")
    !GlobalTimerNotExpired("OH_BREACH","LOCALS")
    HasItem("WAND18",Myself)  // Wand of Spell Striking
    GlobalLT("OH_BreachW","LOCALS",6)
    See(ThirdNearest([PC]))
    OR(4)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
    !StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        IncrementGlobal("OH_BreachW","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
        DisplayStringHead(Myself,31971)  // *uses a wand*
        UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
        SetInterrupt(TRUE)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !GlobalTimerNotExpired("OH_TStop","LOCALS")
    !GlobalTimerNotExpired("OH_BREACH","LOCALS")
    HasItem("WAND18",Myself)  // Wand of Spell Striking
    GlobalLT("OH_BreachW","LOCALS",6)
    See(FourthNearest([PC]))
    OR(4)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
    !StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        IncrementGlobal("OH_BreachW","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
        DisplayStringHead(Myself,31971)  // *uses a wand*
        UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
        SetInterrupt(TRUE)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !GlobalTimerNotExpired("OH_TStop","LOCALS")
    !GlobalTimerNotExpired("OH_BREACH","LOCALS")
    HasItem("WAND18",Myself)  // Wand of Spell Striking
    GlobalLT("OH_BreachW","LOCALS",6)
    See(FifthNearest([PC]))
    OR(4)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
    !StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        IncrementGlobal("OH_BreachW","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
        DisplayStringHead(Myself,31971)  // *uses a wand*
        UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
        SetInterrupt(TRUE)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    !GlobalTimerNotExpired("OH_TStop","LOCALS")
    !GlobalTimerNotExpired("OH_BREACH","LOCALS")
    HasItem("WAND18",Myself)  // Wand of Spell Striking
    GlobalLT("OH_BreachW","LOCALS",6)
    See(SixthNearest([PC]))
    OR(4)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
        CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
        CheckStatGT(LastSeenBy(Myself),0,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
        CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
    !StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
THEN
    RESPONSE #100
        SetInterrupt(FALSE)
        IncrementGlobal("OH_BreachW","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetGlobalTimer("OH_BREACH","LOCALS",TWO_ROUNDS)
        DisplayStringHead(Myself,31971)  // *uses a wand*
        UseItem("WAND18",LastSeenBy(Myself))  // Wand of Spell Striking
        SetInterrupt(TRUE)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    See([GOODCUTOFF])
    CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
    HaveSpell(WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    See(SecondNearest([GOODCUTOFF]))
    CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
    HaveSpell(WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    See(ThirdNearest([GOODCUTOFF]))
    CheckStatGT(LastSeenBy(Myself),49,RESISTMAGIC)
    HaveSpell(WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)  // SPWI514.SPL (Lower Resistance)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MORDENKAINENS_SWORD)  // SPWI716.SPL (Mordenkainen's Sword)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_MORDENKAINENS_SWORD)  // SPWI716.SPL (Mordenkainen's Sword)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
    !CheckStat(Myself,1,WIZARD_FIRE_SHIELD)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    OR(2)
        !HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
        StateCheck(Myself,STATE_INVISIBLE)
    RandomNum(4,1)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_FIRE_SHIELD_RED)  // SPWI418.SPL (Fire Shield (Red))
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
    !CheckStatLT([EVILCUTOFF],75,RESISTFIRE)
    !CheckStatLT(SecondNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(ThirdNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FourthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FifthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(SixthNearest([EVILCUTOFF]),75,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See([GOODCUTOFF])
    Range(LastSeenBy(Myself),11)
    CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    HaveSpell(WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
    !CheckStatLT([EVILCUTOFF],75,RESISTFIRE)
    !CheckStatLT(SecondNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(ThirdNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FourthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FifthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(SixthNearest([EVILCUTOFF]),75,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(SecondNearest([GOODCUTOFF]))
    Range(LastSeenBy(Myself),11)
    CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    HaveSpell(WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
    !CheckStatLT([EVILCUTOFF],75,RESISTFIRE)
    !CheckStatLT(SecondNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(ThirdNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FourthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FifthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(SixthNearest([EVILCUTOFF]),75,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(ThirdNearest([GOODCUTOFF]))
    Range(LastSeenBy(Myself),11)
    CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    HaveSpell(WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
    !CheckStatLT([EVILCUTOFF],75,RESISTFIRE)
    !CheckStatLT(SecondNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(ThirdNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FourthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FifthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(SixthNearest([EVILCUTOFF]),75,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(FourthNearest([GOODCUTOFF]))
    Range(LastSeenBy(Myself),11)
    CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    HaveSpell(WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
    !CheckStatLT([EVILCUTOFF],75,RESISTFIRE)
    !CheckStatLT(SecondNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(ThirdNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FourthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FifthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(SixthNearest([EVILCUTOFF]),75,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(FifthNearest([GOODCUTOFF]))
    Range(LastSeenBy(Myself),11)
    CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
END

IF
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    HaveSpell(WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
    !CheckStatLT([EVILCUTOFF],75,RESISTFIRE)
    !CheckStatLT(SecondNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(ThirdNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FourthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(FifthNearest([EVILCUTOFF]),75,RESISTFIRE)
    !CheckStatLT(SixthNearest([EVILCUTOFF]),75,RESISTFIRE)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(SixthNearest([GOODCUTOFF]))
    Range(LastSeenBy(Myself),11)
    CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(Myself,WIZARD_SUN_FIRE)  // SPWI523.SPL (Sunfire)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    Global("OH_MSeq","LOCALS",0)
    !StateCheck(Myself,STATE_SILENCED)
    OR(4)
        See([GOODCUTOFF.0.0.BARD_ALL])
        See([GOODCUTOFF.0.0.DRUID_ALL])
        See([GOODCUTOFF.0.0.CLERIC_ALL])
        See([GOODCUTOFF.0.0.MAGE_ALL])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobal("OH_MSeq","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetSequence(SEQ_CAST)
        DisplayString(Myself,8635)  // Minor Sequencer Activated
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    Global("OH_MSeq","LOCALS",0)
    !StateCheck(Myself,STATE_SILENCED)
    See([GOODCUTOFF])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobal("OH_MSeq","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetSequence(SEQ_CAST)
        DisplayString(Myself,8635)  // Minor Sequencer Activated
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    Global("OH_MSeq","LOCALS",0)
    !StateCheck(Myself,STATE_SILENCED)
    See(SecondNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobal("OH_MSeq","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetSequence(SEQ_CAST)
        DisplayString(Myself,8635)  // Minor Sequencer Activated
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    Global("OH_MSeq","LOCALS",0)
    !StateCheck(Myself,STATE_SILENCED)
    See(ThirdNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobal("OH_MSeq","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetSequence(SEQ_CAST)
        DisplayString(Myself,8635)  // Minor Sequencer Activated
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    Global("OH_MSeq","LOCALS",0)
    !StateCheck(Myself,STATE_SILENCED)
    See(FourthNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobal("OH_MSeq","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetSequence(SEQ_CAST)
        DisplayString(Myself,8635)  // Minor Sequencer Activated
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    Global("OH_MSeq","LOCALS",0)
    !StateCheck(Myself,STATE_SILENCED)
    See(FifthNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobal("OH_MSeq","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetSequence(SEQ_CAST)
        DisplayString(Myself,8635)  // Minor Sequencer Activated
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    !CheckStatGT(Myself,0,AURACLEANSING)
    !GlobalTimerNotExpired("OH_Cast","LOCALS")
    Global("OH_MSeq","LOCALS",0)
    !StateCheck(Myself,STATE_SILENCED)
    See(SixthNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobal("OH_MSeq","LOCALS",1)
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        SetSequence(SEQ_CAST)
        DisplayString(Myself,8635)  // Minor Sequencer Activated
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
        ReallyForceSpell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
    See([GOODCUTOFF])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
    See(SecondNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
    See(ThirdNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
    See(FourthNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
    See(FifthNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
    See(SixthNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_FLAME_ARROW)  // SPWI303.SPL (Flame Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See([PC.0.0.MAGE])
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
    CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(SecondNearest([PC.0.0.MAGE]))
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
    CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See([PC.0.0.MAGE_THIEF])
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
    CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(SecondNearest([PC.0.0.MAGE_THIEF]))
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
    CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See([PC.0.0.BARD])
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
    CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(SecondNearest([PC.0.0.BARD]))
    !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
    CheckStatGT(LastSeenBy(Myself),7,SAVEVSDEATH)
    CheckStatLT(LastSeenBy(Myself),30,RESISTMAGIC)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
    !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
    !HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
    !HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
    !HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CLENCHED_FIST)  // SPWI818.SPL (Bigby's Clenched Fist)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
    OR(4)
        See([GOODCUTOFF.0.0.BARD_ALL])
        See([GOODCUTOFF.0.0.DRUID_ALL])
        See([GOODCUTOFF.0.0.CLERIC_ALL])
        See([GOODCUTOFF.0.0.MAGE_ALL])
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
    See([GOODCUTOFF])
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
    See(SecondNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
    See(ThirdNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
    See(FourthNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
    See(FifthNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
    See(SixthNearest([GOODCUTOFF]))
    CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),55,RESISTACID)
    !HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)  // SPWI211.SPL (Melf's Acid Arrow)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    OR(4)
        See([GOODCUTOFF.0.0.BARD_ALL])
        See([GOODCUTOFF.0.0.DRUID_ALL])
        See([GOODCUTOFF.0.0.CLERIC_ALL])
        See([GOODCUTOFF.0.0.MAGE_ALL])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See([GOODCUTOFF])
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(SecondNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(ThirdNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(FourthNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(FifthNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    OR(2)
        !GlobalTimerNotExpired("OH_Cast","LOCALS")
        CheckStatGT(Myself,0,AURACLEANSING)
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    CheckStatLT(Myself,50,SPELLFAILUREMAGE)
    !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
    !StateCheck(Myself,STATE_SILENCED)
    See(SixthNearest([GOODCUTOFF]))
    !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
    !HasItemEquiped("MISC5X",LastSeenBy(Myself))  // Harper Pin
    !HasItemEquiped("OHRAMUL1",LastSeenBy(Myself))  // Brooch of the Vagrant Blades
    CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
    CheckStatLT(LastSeenBy(Myself),31,RESISTMAGIC)
    CheckStatLT(LastSeenBy(Myself),31,MAGICDAMAGERESISTANCE)
    !CheckStat(LastSeenBy(Myself),2,DEFENSIVE_MODIFIER)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    !CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
THEN
    RESPONSE #100
        SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
        Spell(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
END

IF
    Allegiance(Myself,EVILCUTOFF)
    !AreaType(OUTDOOR)
    !Range(NearestEnemyOf(Myself),30)
    Range(NearestDoor,15)
    OpenState(NearestDoor,FALSE)
THEN
    RESPONSE #100
        MoveToObject(NearestDoor)
        OpenDoor(NearestDoor)
END

IF
    Global("OH_Heal","LOCALS",0)
    Global("OH_Active","LOCALS",1)
    !Detect([GOODCUTOFF])
    InMyArea(Player1)
    !StateCheck(Player1,STATE_REALLY_DEAD)
    !StateCheck(Myself,STATE_BLIND)
    OR(2)
        RandomNum(5,1)
        CombatCounter(0)
THEN
    RESPONSE #100
        MoveToObject(Player1)
END

IF
    !Global("OH_Heal","LOCALS",1)
    Global("OH_Active","LOCALS",1)
    !See([GOODCUTOFF])
THEN
    RESPONSE #100
        RandomWalkContinuous()
END

IF
    Global("OH_Heal","LOCALS",1)
    GlobalTimerNotExpired("OH_Cast","LOCALS")
    See([GOODCUTOFF])
THEN
    RESPONSE #100
        RandomWalkContinuous()
END

IF
    !HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    See(NearestEnemyOf(Myself))
THEN
    RESPONSE #100
        AttackReevaluate(LastSeenBy(Myself),30)
END

IF
    HaveSpell(WIZARD_MAGIC_MISSILE)  // SPWI112.SPL (Magic Missile)
    !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    OR(4)
        HitBy([GOODCUTOFF],CRUSHING)
        HitBy([GOODCUTOFF],PIERCING)
        HitBy([GOODCUTOFF],SLASHING)
        Range([GOODCUTOFF],6)
THEN
    RESPONSE #100
        RandomWalkContinuous()
END
