IF
	Die()
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		CreateVisualEffectObject("SPUNHOLY",Myself)
		DisplayStringHeadDead(Myself,100615)  // TORM, PLEASE... TAKE PITY ON ME! ARGH!
		Wait(1)
		DestroySelf()
		SetInterrupt(TRUE)
END

IF
	Global("OHB_WINGED_GAUNTLET","GLOBAL",1)
	HasItem("OHBGLOV1",Myself)  // The Winged's Gauntlet
THEN
	RESPONSE #100
		DestroyItem("OHBGLOV1")  // The Winged's Gauntlet
		Continue()
END

IF
	Global("OH_Active","LOCALS",0)
	OR(3)
		See(NearestEnemyOf(Myself))
		AttackedBy([ANYONE],DEFAULT)
		TookDamage()
THEN
	RESPONSE #100
		SetGlobal("OH_Active","LOCALS",1)
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		Enemy()
		Shout(ASSIST)
		Continue()
END

IF
	Global("OH_Active","LOCALS",0)
	Heard([EVILCUTOFF],ASSIST)
	Range(LastHeardBy(Myself),25)
THEN
	RESPONSE #100
		SetGlobal("OH_Active","LOCALS",1)
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		Enemy()
		Shout(ASSIST)
		MoveToObject(LastHeardBy(Myself))
END

IF
	OR(4)
		Global("OH_Active","LOCALS",0)
		!Allegiance(Myself,EVILCUTOFF)
		StateCheck(Myself,STATE_IMMOBILE)
		StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!GlobalTimerNotExpired("OH_Rest","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Rest","LOCALS",EIGHT_HOURS)
		ApplySpell(Myself,RESTORE_FULL_HEALTH)  // SPIN746.SPL (No such index)
		Rest()
END

IF
	Global("OH_Active","LOCALS",1)
	!InActiveArea(Myself)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		NoAction()
END

IF
	CheckStat(Myself,0,TRUE_SIGHT)
	!AreaCheck("AR3004")  // Watcher's Keep
	!AreaCheck("AR3008")  // Watcher's Keep -- Baalor (Paladin Sword)
THEN
	RESPONSE #100
		ReallyForceSpell(Myself,CLERIC_TRUE_SIGHT)  // SPPR505.SPL (True Seeing)
		Continue()
END

IF
	CheckStat(Myself,0,PROTECTION_FROM_EVIL)
THEN
	RESPONSE #100
		ReallyForceSpellRES("OHBPROG1",Myself)  // Protection From Good, 10' Radius
		Continue()
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_HEAL)  // SPPR607.SPL (Heal)
	HPPercentLT(Myself,50)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("devaheal",Myself)  // Heal
		RemoveSpell(CLERIC_HEAL)  // SPPR607.SPL (Heal)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
	HPPercentLT(Myself,50)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("ohbresto",Myself)  // Greater Restoration
		RemoveSpell(CLERIC_RESTORATION)  // SPPR713.SPL (Greater Restoration)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(Myself,STATE_BLIND)
		StateCheck(Myself,STATE_POISONED)
	HaveSpell(CLERIC_NEUTRALIZE_POISON)  // SPPR404.SPL (Neutralize Poison)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_NEUTRALIZE_POISON)  // SPPR404.SPL (Neutralize Poison)
		RemoveSpell(CLERIC_NEUTRALIZE_POISON)  // SPPR404.SPL (Neutralize Poison)
		SetInterrupt(TRUE)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(FourthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(FifthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	Global("OH_Cloud","LOCALS",0)
	OR(8)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.MAGE_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
		SpellCast(SixthNearest([GOODCUTOFF.0.0.BARD_ALL]),WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
THEN
	RESPONSE #100
		SetGlobal("OH_Cloud","LOCALS",1)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	Global("OH_Cloud","LOCALS",1)
	HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobal("OH_Cloud","LOCALS",0)
		ForceSpell(LastSeenBy(Myself),CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
		RemoveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	See([EVILCUTOFF])
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		RemoveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	See(SecondNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		RemoveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	See(ThirdNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		RemoveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	See(FourthNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		RemoveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	See(FifthNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		RemoveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
	See(SixthNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_PANIC)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		RemoveSpell(CLERIC_REMOVE_FEAR)  // SPPR108.SPL (Remove Fear)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck([EVILCUTOFF],STATE_STUNNED)
		CheckStatGT([EVILCUTOFF],0,HELD)
	See([EVILCUTOFF])
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		RemoveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(SecondNearest([EVILCUTOFF]),STATE_STUNNED)
		CheckStatGT(SecondNearest([EVILCUTOFF]),0,HELD)
	See(SecondNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		RemoveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(ThirdNearest([EVILCUTOFF]),STATE_STUNNED)
		CheckStatGT(ThirdNearest([EVILCUTOFF]),0,HELD)
	See(ThirdNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		RemoveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(FourthNearest([EVILCUTOFF]),STATE_STUNNED)
		CheckStatGT(FourthNearest([EVILCUTOFF]),0,HELD)
	See(FourthNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		RemoveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(FifthNearest([EVILCUTOFF]),STATE_STUNNED)
		CheckStatGT(FifthNearest([EVILCUTOFF]),0,HELD)
	See(FifthNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		RemoveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	OR(2)
		StateCheck(SixthNearest([EVILCUTOFF]),STATE_STUNNED)
		CheckStatGT(SixthNearest([EVILCUTOFF]),0,HELD)
	See(SixthNearest([EVILCUTOFF]))
	HaveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
	!GlobalTimerNotExpired("OH_RParal","LOCALS")
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_RParal","LOCALS",TWO_ROUNDS)
		ForceSpell(LastSeenBy(Myself),CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		RemoveSpell(CLERIC_REMOVE_PARALYSIS)  // SPPR308.SPL (Remove Paralysis)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	StateCheck(Myself,STATE_POISONED)
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		RemoveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See([EVILCUTOFF])
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		RemoveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(SecondNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		RemoveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(ThirdNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		RemoveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(FourthNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		RemoveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(FifthNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		RemoveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See(SixthNearest([EVILCUTOFF]))
	StateCheck(LastSeenBy(Myself),STATE_POISONED)
	!StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
	!StateCheck(LastSeenBy(Myself),STATE_CHARMED)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	HaveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		RemoveSpell(CLERIC_SLOW_POISON)  // SPPR212.SPL (Slow Poison)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See([GOODCUTOFF.0.0.0.0.ILLUSIONARY])
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	See([GOODCUTOFF.0.MIST.0.0.SUMMONED])
	HasItem("NISHRUU",LastSeenBy(Myself))  // Attack
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	OR(4)
		See([GOODCUTOFF.0.0.CLERIC_ALL])
		See([GOODCUTOFF.0.0.DRUID_ALL])
		See([GOODCUTOFF.0.0.BARD_ALL])
		See([GOODCUTOFF.0.0.MAGE_ALL])
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	OR(4)
		See(SecondNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
		See(SecondNearest([GOODCUTOFF.0.0.DRUID_ALL]))
		See(SecondNearest([GOODCUTOFF.0.0.BARD_ALL]))
		See(SecondNearest([GOODCUTOFF.0.0.MAGE_ALL]))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	OR(4)
		See(ThirdNearest([GOODCUTOFF.0.0.CLERIC_ALL]))
		See(ThirdNearest([GOODCUTOFF.0.0.DRUID_ALL]))
		See(ThirdNearest([GOODCUTOFF.0.0.BARD_ALL]))
		See(ThirdNearest([GOODCUTOFF.0.0.MAGE_ALL]))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	See(SeventhNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	See(EighthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	See(NinthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!GlobalTimerNotExpired("OH_Displ","LOCALS")
	See(TenthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),34,LEVEL)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL2)
	CheckStatLT(LastSeenBy(Myself),34,LEVEL3)
	!CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_IMMUNITY)
	OR(17)
		CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
		StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
		CheckStatGT(LastSeenBy(Myself),0,TRUE_SIGHT)
		CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_RESIST_FEAR)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_DEFENSIVE_HARMONY)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
		CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
		CheckStatGT(LastSeenBy(Myself),0,WIZARD_FIRE_SHIELD)
		CheckStatGT(LastSeenBy(Myself),0,DEATH_WARD)
		CheckStatGT(LastSeenBy(Myself),0,DEFENSIVE_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),0,STRENGTH_MODIFIER)
		CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
		HasItemEquiped("BLAKBLAD",LastSeenBy(Myself))  // Black Blade of Disaster
		HasItemEquiped("HARM",LastSeenBy(Myself))  // Harm
		HasItemEquiped("SLAYLIVE",LastSeenBy(Myself))  // Slay Living
		HasItemEquiped("MELFMET",LastSeenBy(Myself))  // Melf's Minute Meteor
	!StateCheck(NearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(SeventhNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(EighthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(NinthNearestEnemyOf(Myself),STATE_DISABLED)
	!StateCheck(TenthNearestEnemyOf(Myself),STATE_DISABLED)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Displ","LOCALS",THREE_ROUNDS)
		ForceSpellRES("OHBWI302",LastSeenBy(Myself))  // Remove Magic
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
	CheckStatLT(Myself,10,MAGICDAMAGERESISTANCE)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
		RemoveSpell(CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
	!StateCheck(Myself,STATE_DRAWUPONHOLYMIGHT)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
		RemoveSpell(CLERIC_DRAW_UPON_HOLY_MIGHT)  // SPPR214.SPL (Draw Upon Holy Might)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
	DifficultyGT(EASY)
	OR(4)
		Range([GOODCUTOFF.0.0.MAGE_ALL.0.0.MASK_GOOD],12)
		Range([GOODCUTOFF.0.0.CLERIC_ALL.0.0.MASK_GOOD],12)
		Range([GOODCUTOFF.0.0.DRUID_ALL.0.0.MASK_GOOD],12)
		Range([GOODCUTOFF.0.0.BARD_ALL.0.0.MASK_GOOD],12)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
		RemoveSpell(CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
		SetInterrupt(TRUE)
END

IF
	GlobalLT("OH_Bladeb","LOCALS",3)
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_BLADE_BARRIER)  // SPPR603.SPL (Blade Barrier)
	CheckStat(Myself,0,CLERIC_BLADE_BARRIER)
	Range(NearestEnemyOf(Myself),12)
	!Difficulty(EASIEST)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		SetSequence(SEQ_CAST)
		ReallyForceSpell(Myself,NPC_BLADE_BARRIER)  // SPPR698.SPL (Blade Barrier)
		RemoveSpell(CLERIC_BLADE_BARRIER)  // SPPR603.SPL (Blade Barrier)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	DifficultyGT(EASY)
	HaveSpell(CLERIC_EARTHQUAKE)  // SPPR720.SPL (Earthquake)
	NumCreatureGT([GOODCUTOFF],2)
	Range([GOODCUTOFF],12)
	Range(SecondNearest([GOODCUTOFF]),12)
	Range(ThirdNearest([GOODCUTOFF]),12)
	OR(3)
		CheckStatGT([GOODCUTOFF],4,LEVEL)
		CheckStatGT([GOODCUTOFF],4,LEVEL2)
		CheckStatGT([GOODCUTOFF],4,LEVEL3)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("ohbquake",Myself)  // Earthquake
		RemoveSpell(CLERIC_EARTHQUAKE)  // SPPR720.SPL (Earthquake)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	DifficultyGT(EASY)
	See(NearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		RemoveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	DifficultyGT(EASY)
	See(SecondNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		RemoveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	DifficultyGT(EASY)
	See(ThirdNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		RemoveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	DifficultyGT(EASY)
	See(FourthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		RemoveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	DifficultyGT(EASY)
	See(FifthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		RemoveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
	DifficultyGT(EASY)
	See(SixthNearestEnemyOf(Myself))
	CheckStatLT(LastSeenBy(Myself),55,RESISTFIRE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),WIZARD_COMET)  // SPWI925.SPL (Comet)
		RemoveSpell(WIZARD_COMET)  // SPWI925.SPL (Comet)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
	See([PC.0.0.MAGE_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		RemoveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
	See(SecondNearest([PC.0.0.MAGE_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		RemoveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
	See(ThirdNearest([PC.0.0.MAGE_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		RemoveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
	See([PC.0.0.CLERIC_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		RemoveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
	See(SecondNearest([PC.0.0.CLERIC_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		RemoveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
	See(ThirdNearest([PC.0.0.CLERIC_ALL]))
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		RemoveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
	See([PC.0.0.DRUID_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		RemoveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
	See([PC.0.0.BARD_ALL])
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_INSECT_PLAGUE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		RemoveSpell(CLERIC_INSECT_PLAGUE)  // SPPR517.SPL (Insect Plague)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
	!Difficulty(EASIEST)
	See([GOODCUTOFF.0.0.0.0.0.MASK_GOOD])
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		RemoveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
	!Difficulty(EASIEST)
	See(SecondNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		RemoveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
	!Difficulty(EASIEST)
	See(ThirdNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		RemoveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
	!Difficulty(EASIEST)
	See(FourthNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		RemoveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
	!Difficulty(EASIEST)
	See(FifthNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		RemoveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
	!Difficulty(EASIEST)
	See(SixthNearest([GOODCUTOFF.0.0.0.0.0.MASK_GOOD]))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),55,MAGICDAMAGERESISTANCE)
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("clck26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(LastSeenBy(Myself),CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		RemoveSpell(CLERIC_UNHOLY_BLIGHT)  // SPPR314.SPL (Unholy Blight)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
	!CheckStatGT(Myself,0,DEATH_WARD)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
		RemoveSpell(CLERIC_DEATH_WARD)  // SPPR409.SPL (Death Ward)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FREE_ACTION)  // SPPR403.SPL (Free Action)
	!CheckStatGT(Myself,0,CLERIC_FREE_ACTION)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,CLERIC_FREE_ACTION)  // SPPR403.SPL (Free Action)
		RemoveSpell(CLERIC_FREE_ACTION)  // SPPR403.SPL (Free Action)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	HaveSpell(WIZARD_MASS_INVISIBILITY)  // SPWI721.SPL (Mass Invisibility)
	!CheckStatGT(Player1,0,TRUE_SIGHT)
	!CheckStatGT(Player2,0,TRUE_SIGHT)
	!CheckStatGT(Player3,0,TRUE_SIGHT)
	!CheckStatGT(Player4,0,TRUE_SIGHT)
	!CheckStatGT(Player5,0,TRUE_SIGHT)
	!CheckStatGT(Player6,0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.PLANATAR],0,TRUE_SIGHT)
	!CheckStatGT([GOODCUTOFF.0.DARKPLANATAR],0,TRUE_SIGHT)
	OR(3)
		Range([EVILCUTOFF],12)
		Range(SecondNearest([EVILCUTOFF]),12)
		RandomNum(4,1)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpell(Myself,WIZARD_MASS_INVISIBILITY)  // SPWI721.SPL (Mass Invisibility)
		RemoveSpell(WIZARD_MASS_INVISIBILITY)  // SPWI721.SPL (Mass Invisibility)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
	!Difficulty(EASIEST)
	See(NearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		ForceSpell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
	!Difficulty(EASIEST)
	See(SecondNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		ForceSpell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
	!Difficulty(EASIEST)
	See(ThirdNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		ForceSpell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
	!Difficulty(EASIEST)
	See(FourthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		ForceSpell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
	!Difficulty(EASIEST)
	See(FifthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		ForceSpell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	HaveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
	!Difficulty(EASIEST)
	See(SixthNearestEnemyOf(Myself))
	!StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatLT(LastSeenBy(Myself),75,RESISTFIRE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),6,WIZARD_SPELL_IMMUNITY)
	!HasItemEquiped("CLCK26",LastSeenBy(Myself))  // Cloak of Mirroring
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		ForceSpell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)  // SPPR503.SPL (Flame Strike)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!Difficulty(EASIEST)
	HaveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
	See(NearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),ELEMENTAL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +3
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	!HasItemEquipedReal("BLUN30",SixthNearest([GOODCUTOFF.HUMANOID]))  // Flail of Ages +5
	!HasItemEquipedReal("SPER12",SixthNearest([GOODCUTOFF.HUMANOID]))  // Ixil's Spike +6
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
		ForceSpell(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_STUN)  // SPWI898.SPL (Symbol, Stun)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!Difficulty(EASIEST)
	HaveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
	See(SecondNearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),ELEMENTAL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +3
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	!HasItemEquipedReal("BLUN30",SixthNearest([GOODCUTOFF.HUMANOID]))  // Flail of Ages +5
	!HasItemEquipedReal("SPER12",SixthNearest([GOODCUTOFF.HUMANOID]))  // Ixil's Spike +6
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
		ForceSpell(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_STUN)  // SPWI898.SPL (Symbol, Stun)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!Difficulty(EASIEST)
	HaveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
	See(ThirdNearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),ELEMENTAL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +3
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	!HasItemEquipedReal("BLUN30",SixthNearest([GOODCUTOFF.HUMANOID]))  // Flail of Ages +5
	!HasItemEquipedReal("SPER12",SixthNearest([GOODCUTOFF.HUMANOID]))  // Ixil's Spike +6
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
		ForceSpell(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_STUN)  // SPWI898.SPL (Symbol, Stun)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!Difficulty(EASIEST)
	HaveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
	See(FourthNearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),ELEMENTAL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +3
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	!HasItemEquipedReal("BLUN30",SixthNearest([GOODCUTOFF.HUMANOID]))  // Flail of Ages +5
	!HasItemEquipedReal("SPER12",SixthNearest([GOODCUTOFF.HUMANOID]))  // Ixil's Spike +6
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
		ForceSpell(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_STUN)  // SPWI898.SPL (Symbol, Stun)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!Difficulty(EASIEST)
	HaveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
	See(FifthNearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),ELEMENTAL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +3
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	!HasItemEquipedReal("BLUN30",SixthNearest([GOODCUTOFF.HUMANOID]))  // Flail of Ages +5
	!HasItemEquipedReal("SPER12",SixthNearest([GOODCUTOFF.HUMANOID]))  // Ixil's Spike +6
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
		ForceSpell(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_STUN)  // SPWI898.SPL (Symbol, Stun)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	!Difficulty(EASIEST)
	HaveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
	See(SixthNearestEnemyOf(Myself))
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Race(LastSeenBy(Myself),ELEMENTAL)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSSPELL)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),2,WIZARD_SPELL_IMMUNITY)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!HasItem("MORSWORD",LastSeenBy(Myself))  // Mordenkainen's Sword
	!HasItemEquipedReal("NPSW01",LastSeenBy(Myself))  // Sword of Arvoreen +3
	!HasItemEquipedReal("SW1H27",LastSeenBy(Myself))  // Arbane's Sword of Agility +2
	!HasItemEquiped("RING09",LastSeenBy(Myself))  // Edventar's Gift
	!HasItemEquipedReal("SW2H06",LastSeenBy(Myself))  // Spider's Bane +2
	!HasItemEquipedReal("BLUN30",SixthNearest([GOODCUTOFF.HUMANOID]))  // Flail of Ages +5
	!HasItemEquipedReal("SPER12",SixthNearest([GOODCUTOFF.HUMANOID]))  // Ixil's Spike +6
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(CLERIC_SYMBOL_STUN)  // SPPR718.SPL (Symbol, Stun)
		ForceSpell(LastSeenBy(Myself),WIZARD_NPC_SYMBOL_STUN)  // SPWI898.SPL (Symbol, Stun)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	OR(5)
		See([PC.0.0.MAGE_ALL])
		See([PC.0.0.BARD_ALL])
		See([PC.0.0.DRUID_ALL])
		See([PC.0.0.CLERIC_ALL])
		See([PC.0.0.FIGHTER_ALL])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		ForceSpell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See([PC])
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		ForceSpell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See(SecondNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		ForceSpell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See(ThirdNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		ForceSpell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See(FourthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		ForceSpell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See(FifthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		ForceSpell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		SetInterrupt(TRUE)
END

IF
	OR(2)
		!GlobalTimerNotExpired("OH_Cast","LOCALS")
		CheckStatGT(Myself,0,AURACLEANSING)
	HaveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
	See(SixthNearest([PC]))
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStatGT(LastSeenBy(Myself),-2,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_CHAOTIC_COMMANDS)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!CheckStat(LastSeenBy(Myself),1,OFFENSIVE_MODIFIER)
	!CheckStat(LastSeenBy(Myself),4,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		RemoveSpell(WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		ForceSpell(LastSeenBy(Myself),WIZARD_FEEBLEMIND)  // SPWI509.SPL (Feeblemind)
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See([PC.0.0.MAGE])
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.MAGE]))
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See([PC.0.0.THIEF])
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.THIEF]))
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See([PC.0.0.MAGE_THIEF])
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.MAGE_THIEF]))
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See([PC.0.0.BARD_ALL])
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See(SecondNearest([PC.0.0.BARD_ALL]))
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See(NearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See(SecondNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See(ThirdNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See(FourthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See(FifthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	!Difficulty(EASIEST)
	See(SixthNearestEnemyOf(Myself))
	Range(LastSeenBy(Myself),6)
	!General(LastSeenBy(Myself),UNDEAD)
	!Race(LastSeenBy(Myself),DEMONIC)
	!Class(LastSeenBy(Myself),MONK)
	!StateCheck(LastSeenBy(Myself),STATE_SLOWED)
	CheckStatGT(LastSeenBy(Myself),-4,SAVEVSDEATH)
	CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
	CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
	!CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
	!CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
	!HasItemEquiped("MISC8J",LastSeenBy(Myself))  // Boots of the West
	!HasItemEquiped("RING39",LastSeenBy(Myself))  // Ring of Gaxx
	!CheckStat(LastSeenBy(Myself),7,WIZARD_SPELL_IMMUNITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBCDIS",LastSeenBy(Myself))  // Cause Disease
END

IF
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	OR(6)
		See(Player1)
		See(Player2)
		See(Player3)
		See(Player4)
		See(Player5)
		See(Player6)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(SixthNearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(FifthNearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(FourthNearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(ThirdNearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(SecondNearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(NearestEnemyOf(Myself),STATE_PANIC)
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING)
	CheckStatLT(NearestEnemyOf(Myself),1,STONESKINS)
	!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!StateCheck(WorstAC([PC]),STATE_PANIC)
	!StateCheck(WorstAC([PC]),STATE_MIRRORIMAGE)
	!CheckStatGT(WorstAC([PC]),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	CheckStatLT(WorstAC([PC]),100,RESISTSLASHING)
	CheckStatLT(WorstAC([PC]),1,STONESKINS)
	See(WorstAC([PC]))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	AttackedBy(NearestEnemyOf(Myself),DEFAULT)
	!CheckStatGT(LastAttackerOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(LastAttackerOf(Myself),STATE_PANIC)
	CheckStatLT(LastAttackerOf(Myself),100,RESISTSLASHING)
	!StateCheck(LastAttackerOf(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastAttackerOf(Myself),1,STONESKINS)
	Range(LastAttackerOf(Myself),8)
	RandomNum(3,1)
	See(LastAttackerOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	AttackedBy(NearestEnemyOf(Myself),DEFAULT)
	!CheckStatGT(LastAttackerOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	!StateCheck(LastAttackerOf(Myself),STATE_PANIC)
	CheckStatLT(LastAttackerOf(Myself),100,RESISTSLASHING)
	!StateCheck(LastAttackerOf(Myself),STATE_MIRRORIMAGE)
	CheckStatLT(LastAttackerOf(Myself),1,STONESKINS)
	Range(LastAttackerOf(Myself),4)
	See(LastAttackerOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(SixthNearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(SixthNearestEnemyOf(Myself),100,RESISTSLASHING)
	See(SixthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(FifthNearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(FifthNearestEnemyOf(Myself),100,RESISTSLASHING)
	See(FifthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(FourthNearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(FourthNearestEnemyOf(Myself),100,RESISTSLASHING)
	See(FourthNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(ThirdNearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(ThirdNearestEnemyOf(Myself),100,RESISTSLASHING)
	See(ThirdNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(SecondNearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(SecondNearestEnemyOf(Myself),100,RESISTSLASHING)
	See(SecondNearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(NearestEnemyOf(Myself),STATE_IMMOBILE)
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTSLASHING)
	See(NearestEnemyOf(Myself))
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player6,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player6,STATE_IMMOBILE)
	CheckStatLT(Player6,100,RESISTSLASHING)
	See(Player6)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player5,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player5,STATE_IMMOBILE)
	CheckStatLT(Player5,100,RESISTSLASHING)
	See(Player5)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player4,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player4,STATE_IMMOBILE)
	CheckStatLT(Player4,100,RESISTSLASHING)
	See(Player4)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player3,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player3,STATE_IMMOBILE)
	CheckStatLT(Player3,100,RESISTSLASHING)
	See(Player3)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player2,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player2,STATE_IMMOBILE)
	CheckStatLT(Player2,100,RESISTSLASHING)
	See(Player2)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!CheckStatGT(Player1,3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	StateCheck(Player1,STATE_IMMOBILE)
	CheckStatLT(Player1,100,RESISTSLASHING)
	See(Player1)
	False()
THEN
	RESPONSE #100
		NoAction()
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	InMyArea(LastSeenBy(Myself))
	!Range(LastSeenBy(Myself),15)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!CheckStatGT(LastSeenBy(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBTELWE",LastSeenBy(Myself))  // Teleport Without Error
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OH_Cast","LOCALS")
	Exists(LastAttackerOf(Myself))
	!Range(LastAttackerOf(Myself),15)
	InMyArea(LastAttackerOf(Myself))
	Allegiance(LastAttackerOf(Myself),GOODCUTOFF)
	!StateCheck(LastAttackerOf(Myself),STATE_REALLY_DEAD)
	!CheckStatGT(LastAttackerOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
	CheckStatLT(LastAttackerOf(Myself),100,RESISTSLASHING)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_Cast","LOCALS",ONE_ROUND)
		ForceSpellRES("OHBTELWE",LastAttackerOf(Myself))  // Teleport Without Error
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,EVILCUTOFF)
	!AreaType(OUTDOOR)
	!Range(NearestEnemyOf(Myself),30)
	Range(NearestDoor,15)
	OpenState(NearestDoor,FALSE)
THEN
	RESPONSE #100
		MoveToObject(NearestDoor)
		OpenDoor(NearestDoor)
END

IF
	Global("OH_Heal","LOCALS",0)
	Global("OH_Active","LOCALS",1)
	!Range([GOODCUTOFF],30)
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	!StateCheck(Myself,STATE_BLIND)
	!StateCheck(Player1,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	Global("OH_Heal","LOCALS",0)
	Global("OH_Active","LOCALS",1)
	!Range([GOODCUTOFF],30)
	!Detect([GOODCUTOFF])
	InMyArea(Player1)
	!StateCheck(Myself,STATE_BLIND)
	!StateCheck(Player1,STATE_REALLY_DEAD)
	OR(2)
		RandomNum(5,1)
		CombatCounter(0)
THEN
	RESPONSE #100
		MoveToObject(Player1)
END

IF
	!Global("OH_Heal","LOCALS",1)
	Global("OH_Active","LOCALS",1)
	!Range([GOODCUTOFF],30)
	!See([GOODCUTOFF])
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	!Allegiance(LastSeenBy(Myself),EVILCUTOFF)
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),15)
END

