IF
	Dead("ohbvoghi")  // Voghiln the Vast
THEN
	RESPONSE #100
		DestroySelf()
END

IF
	Global("OHB_START_BATTLE","GLOBAL",2)
	OR(3)
		AreaCheck("OH8200")  // TBP2 - Arena 1
		AreaCheck("OH8300")  // TBP2 - Arena 2
		AreaCheck("OH8400")  // TBP2 - Arena 3
THEN
	RESPONSE #100
		NoAction()
END

IF
	Global("ohb_voghiln_hired","global",3)
	!AreaCheck("oh8100")  // TBP2 - Staging Area Map
THEN
	RESPONSE #100
		SetGlobal("ohb_voghiln_hired","global",4)
		EquipRanged()
END

IF
	Global("OHB_TALKED_VOGHI","LOCALS",1)
	Global("OHB_DINNERBELL","OH8100",0)  // TBP2 - Staging Area Map
	Global("OHB_VOGHI_WALK","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("OHB_VOGHI_WALK","LOCALS",1)
		MoveToPointNoInterrupt([2260.1645])
		Face(SW)
END

