IF
    True()
THEN
    RESPONSE #100
	    SetGlobal("ZBPODSTART","GLOBAL",2)
        CutSceneId(Player1) 
        FadeToColor([20.0],0)
        Wait(1)
        LeaveAreaLUAPanic("OH8000","",[697.458],NW)  
        LeaveAreaLUA("OH8000","",[697.458],NW)  
        ActionOverride(Player2,LeaveAreaLUA("OH8000","",[766.482],NW))  
        ActionOverride(Player3,LeaveAreaLUA("OH8000","",[592.533],NW))  
        ActionOverride(Player4,LeaveAreaLUA("OH8000","",[653.577],NW))  
        ActionOverride(Player5,LeaveAreaLUA("OH8000","",[701.596],NW))  
        ActionOverride(Player6,LeaveAreaLUA("OH8000","",[744.557],NW))  
		FadeFromColor([30.0],0) 
        EndCutSceneMode()
END
