/* not currently being compiled - bucket, 20241111 */ 

IF
    True()
THEN
    RESPONSE #100
	    SetGlobal("ZBPODTHAY","GLOBAL",0) 
        CutSceneId(Player1) 
        FadeToColor([20.0],0)
        Wait(1)
        LeaveAreaLUAPanic("OH8100","",[2476.1408],NW)  
        LeaveAreaLUA("OH8100","",[2476.1408],NW)  
        ActionOverride(Player2,LeaveAreaLUA("OH8100","",[2441.1373],NW))  
		ActionOverride(Player3,LeaveAreaLUA("OH8100","",[2518.1385],NW)) 
        ActionOverride(Player4,LeaveAreaLUA("OH8100","",[2500.1348],NW))  
        ActionOverride(Player5,LeaveAreaLUA("OH8100","",[2574.1361],NW))  
        ActionOverride(Player6,LeaveAreaLUA("OH8100","",[2543.1322],NW))  
		FadeFromColor([30.0],0) 
        EndCutSceneMode()
END
