/* not currently being compiled - bucket, 20241111 */ 

IF
    True()
THEN
    RESPONSE #100
	    SetGlobal("ZBPODTRADES","GLOBAL",0) 
        CutSceneId(Player1) 
        FadeToColor([20.0],0)
        Wait(1)
        LeaveAreaLUAPanic("AR2010","",[455.671],NW)  
        LeaveAreaLUA("AR2010","",[455.671],NW)  
        ActionOverride(Player2,LeaveAreaLUA("AR2010","",[408.631],NW))  
		ActionOverride(Player3,LeaveAreaLUA("AR2010","",[505.632],NW)) 
        ActionOverride(Player4,LeaveAreaLUA("AR2010","",[457.592],NW))  
        ActionOverride(Player5,LeaveAreaLUA("AR2010","",[346.632],NW))  
        ActionOverride(Player6,LeaveAreaLUA("AR2010","",[425.677],NW))  
		FadeFromColor([30.0],0) 
        EndCutSceneMode()
END
