/* messenger approaches and starts the dialogue */ 
IF
Global("ZBPodSummonsReceived","GLOBAL",2)
See([PC])
THEN
RESPONSE #100
SetGlobal("ZBPodSummonsReceived","GLOBAL",3)
MoveToObject([PC])
StartDialogueNoSet(Player1)
END

/* if the messenger, for some reason, can't see CHARNAME
despite being spawned next to them
scoot back over */ 
IF
Global("ZBPodSummonsReceived","GLOBAL",2)
!See([PC])
THEN
RESPONSE #100
MoveToObject([PC])
END

IF
  Global("ZBPodSummonsReceived","GLOBAL",4)
THEN
  RESPONSE #100
    EscapeArea()
END 
  
