IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		SetGlobal("OHB_BP2_CAPTURE","GLOBAL",1)
		ChangeAIScript("OHBPLOT",OVERRIDE)
		ApplySpellRES("SPBP001",Player1)  // No such index
		ApplySpellRES("SPBP001",Player2)  // No such index
		ApplySpellRES("SPBP001",Player3)  // No such index
		ApplySpellRES("SPBP001",Player4)  // No such index
		ApplySpellRES("SPBP001",Player5)  // No such index
		ApplySpellRES("SPBP001",Player6)  // No such index
		CreateCreature("cutspy",[340.660],NE)
		CreateCreature("ohbjoker",[585.473],SE)  // Joker
		ActionOverride("ohbjoker",Polymorph(NOBLE_WOMAN))
		ActionOverride("ohbjoker",SetName(1083))  // Bard
		CreateCreature("ohbdorma",[505.390],SE)  // Dormamus
		ActionOverride("ohbdorma",Polymorph(STATIC_PEASANT_MAN_CHAIR))
		ActionOverride("ohbdorma",SetName(93613))  // Fan
		ActionOverride("ohbdorma",FaceObject("ohbjoker"))
		CreateCreature("ohbbanno",[880.560],E)  // Bannor
		ActionOverride("ohbbanno",Polymorph(PEASANT_MAN))
		ActionOverride("ohbbanno",SetName(93613))  // Fan
		ActionOverride("ohbbanno",FaceObject("ohbjoker"))
		CreateCreature("ohbthass",[560.600],N)  // Thassk Kun
		ActionOverride("ohbthass",Polymorph(STATIC_PEASANT_MAN_CHAIR))
		ActionOverride("ohbthass",SetName(93613))  // Fan
		ActionOverride("ohbthass",FaceObject("ohbjoker"))
		CreateCreature("ohbpol",[725.620],NW)  // Pol Pyrrus
		ActionOverride("ohbpol",Polymorph(STATIC_PEASANT_MAN_CHAIR))
		ActionOverride("ohbpol",SetName(93613))  // Fan
		ActionOverride("ohbpol",FaceObject("ohbjoker"))
		SmallWait(25)
		JumpToPoint([697.458])
		ActionOverride(Player2,JumpToPoint([766.482]))
		ActionOverride(Player3,JumpToPoint([592.533]))
		ActionOverride(Player4,JumpToPoint([653.577]))
		ActionOverride(Player5,JumpToPoint([701.596]))
		ActionOverride(Player6,JumpToPoint([744.557]))
		FaceObject("ohbjoker")  // Joker
		ActionOverride(Player2,FaceObject("ohbjoker"))  // Joker
		ActionOverride(Player3,FaceObject("ohbjoker"))  // Joker
		ActionOverride(Player4,FaceObject("ohbjoker"))  // Joker
		ActionOverride(Player5,FaceObject("ohbjoker"))  // Joker
		ActionOverride(Player6,FaceObject("ohbjoker"))  // Joker
		MoveViewPoint([672.468],INSTANT)
		SetGlobal("ZBCUT00SKIP_CUTSCENE_BREAKABLE","GLOBAL",1)
		SetAreaScript("zbcut00s",OVERRIDE)
		SetGlobal("ZBBP2inBG2","GLOBAL",1)
		SetGlobal("OHB_TALKED_BELLOWGULP","GLOBAL",1)
		SmallWait(1)
		SetCutSceneBreakable(TRUE)
		FadeFromColor([60.0],0)
		DisplayStringHead("ohbjoker",@2)  // Along the Sword Coast they traveled, battling all kinds of horrible creatures. Investigating matters of tainted iron and politics, only to discover their own Bhaalspawn blood behind it.
		Wait(6)
		DisplayStringHead("ohbjoker",@35)  // Baldur’s Gate held its breath as a battle of godly heritage unraveled beneath the ground. But they rose to the challenge, ending the crisis, and became heroes to the city.
		Wait(6)
		DisplayStringHead("OHBTHASS",@7)  // A decent yarn, though a bit TOO fantastic if you ask me.
		Wait(5)
		DisplayStringHead("OHBJOKER",@8)  // Thank you. It is an amazing tale, all the more so for the fact that it actually happened.
		Wait(5)
		DisplayStringHead("OHBPOL",@9)  // You are a talented entertainer, madam, but do not insult my intelligence. The story you told is naught but a story. It never happened.
		Wait(7)
		SetCutSceneBreakable(FALSE)
		SetAreaScript("",OVERRIDE)
		ActionOverride("ohbjoker",StartDialogueNoSet(Player1))
END

