IF
  Global("ZB_NEPH_ESCAPE_1","GLOBAL",1)
THEN
  RESPONSE #100
    CutSceneId(Player1)
    SetCutSceneBreakable(FALSE)
    SetGlobal("ZB_NEPH_ESCAPE_1","GLOBAL",2)
    DisplayStringHead("zbneph",@101) /* Now just let me fit this ring on your finger gah… well maybe this way? Ah, that's it. Hold on to your belongings… off to Amn we go! Ala-khazoom! */
    Wait(4)
    ApplySpellRES("OHBAMREM",Player1)  // No such index
    ApplySpellRES("OHBAMREM",Player2)  // No such index
    ApplySpellRES("OHBAMREM",Player3)  // No such index
    ApplySpellRES("OHBAMREM",Player4)  // No such index
    ApplySpellRES("OHBAMREM",Player5)  // No such index
    ApplySpellRES("OHBAMREM",Player6)  // No such index
    SetGlobal("OHB_ANTIMAGIC","GLOBAL",0)
    ActionOverride("zbneph",ReallyForceSpell(Myself,DRYAD_TELEPORT))
    SmallWait(25)
    LeaveAreaLUAPanic("AR2010","",[410.640],W)
    LeaveAreaLUA("AR2010","",[410.640],W)
    ActionOverride(Player2,LeaveAreaLUA("AR2010","",[420.640],W))
    ActionOverride(Player3,LeaveAreaLUA("AR2010","",[430.640],W))
    ActionOverride(Player4,LeaveAreaLUA("AR2010","",[410.650],W))
    ActionOverride(Player5,LeaveAreaLUA("AR2010","",[420.650],W))
    ActionOverride(Player6,LeaveAreaLUA("AR2010","",[430.650],W))
    MultiPlayerSync()
    SmallWait(25)
    EndCutSceneMode()
    SaveGame(0)
END
