IF
    Die()
THEN
    RESPONSE #100
        CreateVisualEffectObject("SPUNHOLY",Myself)
        DestroySelf()
END

IF
    Global("OHB_BhaalH","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("OHB_BhaalH","LOCALS",1)
        ReallyForceSpellRES("ohbbclt1",Myself)  // No such index
        Continue()
END

IF
    Global("OH_Active","LOCALS",0)
THEN
    RESPONSE #100
        SetGlobal("OH_Active","LOCALS",1)
        Continue()
END
