IF
	Contains("OHBCOM01",Myself)  // Powdered Funguswood
	Global("OHB_COOK_POISON","GLOBAL",1)
THEN
	RESPONSE #100
		SetGlobal("OHB_COOK_POISON","GLOBAL",2)
		DestroyItem("OHBCOM01")  // Powdered Funguswood
END

IF
	Global("OHB_COOK_MUSHROOM","GLOBAL",3)
	Global("ohb_makesoup","LOCALS",0)
THEN
	RESPONSE #100
		CreateItem("ohbptn11",0,0,0)  // Myconid Soup
		SetGlobal("ohb_makesoup","LOCALS",1)
END

